### ISSUE TITLE
Spike: Metrics for task list page

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#163]
Problem statement

The Pipeline categorises issue types as Error and Warning which could serve as our technical statuses

We may need to add further detail to those technical statuses, such as: Endpoint warning, Row level error

Approach

Meet with George, Alex and Gwen to agree terminology

Acceptance criteria

- Understanding of key phrases
- Agreement on placement of phrases in the service

**Comment by Darren-CheckPlanningData** [comment]
MJ Faucher-Folie [15 minutes ago]
(https://trello.com/c/baP2Tel3/3405-spike-metrics-for-task-list-page#comment-66a9f5c6b269e7ab5fb58cb5)

Closing as designs for page is complete


MJ Faucher-Folie [17 Jul 2024, 13:25]
(https://trello.com/c/baP2Tel3/3405-spike-metrics-for-task-list-page#comment-6697b832732d0ed5d36bd53f)

Host conversation Tuesday 23rd to agree definitions of terms, examples of terms, and list all terms to be used on the Task List Page

‌

Confirm if the dashboard technical statuses will also reflect this
