### ISSUE TITLE
Spike: Where do we get the raw column titles and field values from (Chris, Infra)

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#168]

**Comment by Darren-CheckPlanningData** [comment]
@cpcundill are you ok answering this Spike for Providers team?

**Comment by Darren-CheckPlanningData** [comment]
Need clarification on what the raw columns are. @GeorgeGoodall 
Where are they showing them.

**Comment by cpcundill** [comment]
Assuming, the intention is for the column names contained within a provider's datafile, then the column field log via Datasette is the correct data source.  The Performance API wouldn't be a host of this information.

**Comment by GeorgeGoodall** [comment]
that's perfect! thanks @cpcundill 

cc: @Darren-CheckPlanningData
