### ISSUE TITLE
Spike: KPI Gap Analysis

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#186]
**Problem statement**

We want to begin work to collect metrics to assess the service we’re building, but must understand what KPIs are already being collected to prevent duplication of work.

**Approach**

Conduct research to understand what KPIs are already being tracked

Create a list of data points we want to collect

**Acceptance criteria**

- Artefact detailing what KPIs are being tracked and how
- Artefact detailing the KPIs we want to track and how, and if we are collecting them currently
- KPIs featured in Artefact matches against changes in the OKRs, based on Q2 meeting

**Dependencies**

Q2 Meeting

**Links**
- [Gap analysis of the metrics we're currently capturing and what should be captured](https://docs.google.com/spreadsheets/d/1sp2tTRvfyW4M3tzk7he2iR1tpbUtQm72IaMnwmxYRso/edit?gid=2029545334#gid=2029545334)
- [Identifying what parts of the journey can assist in capturing metrics](https://app.mural.co/t/mhclg2837/m/mhclg2837/1719570696786/cd1dbc71c0e77552f5a622cfce32130b269868e0?wid=95-1720444264944)

**Comment by MJFaucherFolie** [comment]
Output of spike - what do you want to happen with the work
what's next - recommendation, what work needs to happen - solution which needs to be created
spike - answered the question 
output = is thee further work to do be 
Create another spike to address this !

**Comment by CharliePatterson** [comment]
Moving back to backlog - will resume work on this in near future.
