### ISSUE TITLE
Tech Debt: add a new github action for deploying to dev or staging

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#202]
at the moment I dont believe we have any way to deploy a branch other than main to dev or staging, be it either manually or automatically. I propose firstly we add in an action to manually do this. but then further to that add in an automatic action that deploys to staging when the staging branch is update

UPDATE:
have now added an action for manually deploying. however is it a good idea to have automated deploys setup when pushing to the staging or development branch

**Comment by Darren-CheckPlanningData** [comment]
This work should like to Infrastructure OKRs
