### ISSUE TITLE
Bug: 404 page for dashboard

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit#203]
bug when accessing a non existent org

Object.getLpaOverview(src.services:performanceDbApi)
Cannot read properties of undefined (reading '1')

Supporting artefacts:
PR that may offer a fix for this: https://github.com/digital-land/submit.planning.data.gov.uk/pull/340

**Comment by rosado** [comment]
Relevant comment: https://github.com/digital-land/submit.planning.data.gov.uk/issues/238#issuecomment-2315039162
