### ISSUE TITLE
Bug: performanceApi.js cannot read properties of undefined

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#238]
https://planning-data-platform.sentry.io/issues/5686381253/?referrer=slack&notification_uuid=58cecbe3-5fbc-42d2-a0b8-c1a6d32d20d1&alert_rule_id=15340009&alert_type=issue

**Comment by rosado** [comment]
The issue happens in the `getLpaOverview` handler which has been rewritten in #340 so this should be taken care of. But same bug will still occur for `/organisations/:lpa/:dataset` routes - they are waiting for a rewrite as noted in #333
