### ISSUE TITLE
Filter the organisations list on the org finder page

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#253]
## Context:

- The [organisation finder page](https://submit.planning.data.gov.uk/organisations) is the step in the service flow when LPAs select their organisation, so that they can view their dashboard.
- The list on this page should only show organisations that are expected or required to submit data.
- We should show organisations of types `local-authority` and `national-park-authority` from the [project_organisation](https://datasette.planning.data.gov.uk/digital-land/project_organisation) table.

## Acceptance criteria:

- As a data provider, when I'm viewing the organisation finder page, I only see organisations of types `local-authority` and `national-park-authority`.

**Comment by CharliePatterson** [comment]
We need to confirm which organisations are the right ones to show here.

I'm presuming [this list](https://www.planning.data.gov.uk/dataset/#organisation) covers the full range of organisation types? There are 9 listed there - which ones are the ones we want to be listed on the organisation finder page?

1. [Development corporation](https://www.planning.data.gov.uk/dataset/development-corporation)
2. [Government organisation](https://www.planning.data.gov.uk/dataset/government-organisation)
3. [Local authority](https://www.planning.data.gov.uk/dataset/local-authority)
4. [National park authority](https://www.planning.data.gov.uk/dataset/national-park-authority)
5. [Nonprofit organisation](https://www.planning.data.gov.uk/dataset/nonprofit)
6. [Passenger transport executive](https://www.planning.data.gov.uk/dataset/passenger-transport-executive)
7. [Public authority](https://www.planning.data.gov.uk/dataset/public-authority)
8. [Regional park authority](https://www.planning.data.gov.uk/dataset/regional-park-authority)
9. [Waste disposal authority](https://www.planning.data.gov.uk/dataset/waste-authority)

Paging @stevenjmesser @MJFaucherFolie for input - any ideas on this?

**Comment by stevenjmesser** [comment]
Organisations of types `local-authority` and `national-park-authority` currently. You can see that from the [project_organisation](https://datasette.planning.data.gov.uk/digital-land/project_organisation) table.
