### ISSUE TITLE
Spike: Considering how we might weave in some of the things we've learnt from the ODP onboarding journey

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit#257]
Questions to answer:

- [ ] Considering how we might weave in some of the things we've learnt from the ODP onboarding journey, and possibly expanding the onboarding journey on the site to be more than just a landing page. Also considering how we might build in the community aspect?

**Comment by paris-dp** [comment]
I have reviewed content on Notion- some things that would be helpful to build in:
- People who may be involved in the process of providing data within a LPA (in Notion hub this is packaged as building the team for the project) 
- Community element can be useful as learnings are shared. A sense of community for non ODP LPAs will be important. This could include show and tells, blogs, a place to ask questions
