### ISSUE TITLE
Spike:  Options/proposal for how it's accessed

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit#259]
Questions to answer:

- [ ] Options/proposal for how it's accessed: how / where do we link to it from the main site? e.g. does it live under the 'Provide data' navigation link, as part of the main site and we replace the current link? Do we link to it from the current page there? Do we need some kind of interim 'beta' type approach?

**Comment by paris-dp** [comment]
Proposal: At present key word searches lead to planning.data.gov, therefore it feels appropriate to remain linked.
