### ISSUE TITLE
Validating/updating service map

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#260]
What:
Validating end to end service map and amending to give current overview

Problem
Current service map was created some time ago and the landscape may have changed. E.g. tools and processes used

Artefacts 

Current service design
[[Link to Mural board]](https://app.mural.co/t/mhclg2837/m/mhclg2837/1688057194639/d907acbd773bfc9085c1e17b8780498be4fca8c5?sender=u463319bb16378792b5869752)

Tasks

- [x] Validate with Colm - data design 
- [x] Update providers part of the map
- [x] Validate with Swati and Mark - data management
- [x] Colm sign off
- [x] Swati sign off
- [x] Validate with MJ -analysis sign off
- [x] Validate with Owen - platform/infrastructure
- [x] Workshop around pain points
- [x] Final edits before ongoing iteration

**Comment by Darren-CheckPlanningData** [comment]
Working through the task list in description

**Comment by paris-dp** [comment]
Added MJ ahead of meeting to validate and complete
