### ISSUE TITLE
Tech Debt: improve error handling and input validation for methods in the organisation controller

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit#267]
**Why**: The code is brittle, hard to test, and in places it only handles the "happy path" and doesn't deal with potential errors. 

We can remove most of the code duplication and add proper error handling and param validation by decomposing the heavy functions into middlewares. This will also enable us to do actual unit testing (the current unit tests exercising the organisation controller code paths are really integration tests - they can't be run without a hefty dose of mock objects). 

We need to go through all functions in the `organisationController` object and 

- pull them apart into middlewares
- add parameter validatiion
- add proper error handling (including returning 404 when LPA was not found)

The calling code will not see much difference, but related unit tests will also need to be updated.

_Note_: due to it's size, this task has been split into two, with the second part being #333

**Comment by CharliePatterson** [comment]
@rosado @GeorgeGoodall can you please add some context (what this is, why it's valuable / what the benefits are / why we're doing it) and some acceptance criteria?
