### ISSUE TITLE
Bug: Error with date fields

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#278]
A defect found in the system that doesn’t currently have a workaround
Description of the problem it is causing

What were you expecting to see:
- No issues with the date column as it is a date

What are you seeing:
![Image](https://github.com/user-attachments/assets/111fe5fd-0171-4842-bb77-d18443d5ede8)

Who raised it
An LPA

Problem causing
- Preventing the LPA

Additional info
- The LPA has submitted a Conservation area dataset with the same date format and it's been accepted. Their Conservation area document is causing issues

URL

- Conservation area dataset  
https://atlas.peterborough.gov.uk/arcgis/rest/services/Planning/Planning_Digitisation_GOV_UK_External_Connection/MapServer/1/query?outFields=*&where=1%3D1&f=geojson

- Conservation area document dataset 
https://atlas.peterborough.gov.uk/arcgis/rest/services/Planning/Planning_Digitisation_GOV_UK_External_Connection/MapServer/2/query?outFields=*&where=1%3D1&f=json

### Dependencies:
Trello card created for infra: https://trello.com/c/OPdOoS9q

### Supporting artefacts:

Tasks:

- [x] Discuss with infra team as they do the validation on dates in the backend

**Comment by Darren-CheckPlanningData** [comment]
Infra will be looking at this next sprint, details in their trello ticket in description
