### ISSUE TITLE
Devise an experiment plan to manually notify LPAs about data quality issues

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#302]
## Context:

- The data providers dashboard surfaces data quality issues to LPAs, to help them understand how to improve the quality of the data they've submitted to the platform.
- However, unless an LPA is regularly checking their dashboard, they won't know that there are tasks for them to complete.
- As such, there's a need for the platform to notify LPAs of these things, and signpost them to the relevant pages to complete these actions.

## User story:

- As an LPA when there are quality issues with the data we've provided we want to be notified of these so that we can fix them.
- As the planning data platform when there are quality issues with the data an LPA has provided we want them to be notified of these so that they can fix them.

## Outcomes and outputs:

Create a plan for how to tackle this in the short-term.

While we will want to productise this in the long-term (to automate the sending of notifications), in the short-term we should take a more manual approach to test various aspects of this (content, triggers, etc.).

The plan should cover:

- Details of what we plan to test
- How we plan to test it
- What we want to measure / how we'll know whether or not it's successful
- Any questions that need answering prior to starting the work

Some initial thoughts and questions:

- Should we run some split / multivariate testing as part of this?
- What should we include in the notification?
- Where's the right place to send users?
- What does the user journey around this look like?

**Comment by paris-dp** [comment]
Workshopped with MJ to address questions and surface initial [plan](https://app.mural.co/t/mhclg2837/m/mhclg2837/1724323175941/086e283ce666e3b75ce635e311a1b15465bc97e7?wid=0-1724334566453)

**Comment by MJFaucherFolie** [comment]
Drafted plan based on our playback to the team on the 27th: https://docs.google.com/document/d/1eFYaBbhmIP5IOnZ4nYGeaGIu0Mq16xCcHVJ-Kxg3ZAU/edit

**Comment by Darren-CheckPlanningData** [comment]
Blocked due to pushback from community managers not wanting to share email addresses for LPAs.
MJ looking to set up a discussion with Tom (Community manager), Charlie & Steve to resolve the concerns.

**Comment by MJFaucherFolie** [comment]
Had a chat with a senior member of the Community Management team. They have agreed to release the LPA emails, but MJ needs to share with them A) what we need from them, and B) a few lines that they can use to inform LPAs of what to expect

**Comment by MJFaucherFolie** [comment]
Created draft emails for the test:

- [General service message](https://docs.google.com/document/d/1YnrulDYSZMmE9iZoA3hMwgtYByT2br64Ye7U7-9eTYk/edit) 
- [Descriptive service message](https://docs.google.com/document/d/17o3N-5h_QxVt-yCi3qfDum-RJZrkzA-p0Xvl10zP9jg/edit)

**Comment by CharliePatterson** [comment]
Plan created - work split into the following tickets:

- https://github.com/digital-land/submit/issues/427
- https://github.com/digital-land/submit/issues/428
