### ISSUE TITLE
Group issues when entire column is missing

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#306]
## Context:

- The 'issues details page' displays each record within the specified dataset that contains an issue.
- When an entire column is missing from the dataset, displaying every single record that's missing the specified value creates a poor user experience, since we're replicating the same information over and over again.
- Instead, we should tell the user that their dataset is missing a particular column.

## Acceptance criteria:

- As a data provider, when I am on the data issues page, and the dataset I'm looking at is missing a column, the UI tells me that rather than treating these as separate entities, and I know what I need to do to fix that issue.
- As a data provider, when I am on the data issues tasklist page, and the dataset I'm looking at is missing a column, the UI tells me that rather than treating these as separate entities.

Tasks:
- [x] Collate list of error messages
- [x] update get issue details controller method to ensure error summary header is generated correctly
- [x] Split up the tasks by field (as well as issue_type)
- [x] Implement the new messages
- [x] Update existing tests
- [x] add test to ensure that the default 'There is a problem' header is used in the issueDetails template if no header Is provided
- [ ] add test for get entity count **_Going to leave this as the function doesn't do very much_**
- [ ] Content design review of the error messages: _**Going to move this to another ticket: #411 **_

**Comment by alextea** [comment]
I have collated a [list of error messages in this spreadsheet](https://docs.google.com/spreadsheets/d/1hvffB4LuHEHR2WutAxp98CzG0WsZJFlx-2VmGeIM5Yk/edit?gid=813787384#gid=813787384) (under the heading "column level errors")

error type | message
-- | --
column not supplied | `column-name` column is missing
all rows are empty | `column-name` column is missing values
all rows are invalid date | `column-name` column must be in YYYY-MM-DD format
all rows are invalid coordinates | `column-name` column must have valid coordinates
all rows are invalid decimal | `column-name` column must have decimal numbers
all rows are invalid integer | `column-name` column must have valid integers
all rows are too small | `column-name` column must be above the minimum number needed
all rows are too large | `column-name` column must be below the maximum number needed
all rows are invalid flag | `column-name` column must have valid YES or NO values
all rows are invalid URI | `column-name` column must have valid URIs
all rows are invalid WKT | `column-name` column must have valid WKT values
all rows are future entry-date | `column-name` column must be in the past
all rows are WGS84 out of bounds | `column-name` column is WGS84 out of bounds
all rows are invalid geometry - not fixable | `column-name` column must have valid geometry
all rows are Unexpected geom type | `column-name` column must have valid geometry
all rows are Unexpected geom type within GeometryCollection | `column-name` column must have valid geometry
all rows are WGS84 out of bounds of England | `column-name` column must be within England
all rows are WGS84 out of bounds of custom boundary | `column-name` column must be within the specified boundary
all rows are OSGB out of bounds of England | `column-name` column must be within England
all rows are OSGB out of bounds of custom boundary | `column-name` column must be within the specified boundary
reference values are not unique | `column-name` column must have unique entries

**Comment by CharliePatterson** [comment]
@alextea has there been a content design review of these?

@GeorgeGoodall is there anything else you need to implement this? Is the information in this ticket sufficient?

**Comment by alextea** [comment]
@CharliePatterson not yet, but they are based on messages Gwen had written previously

**Comment by GeorgeGoodall** [comment]
@alextea @CharliePatterson I think it makes sense also to update the content on the dataset issues page


![Image](https://github.com/user-attachments/assets/0cfa9989-4c7d-452e-aad6-e5d1392db86e)

This ok with you both?

**Comment by CharliePatterson** [comment]
Good shout @GeorgeGoodall - that's all good with me.

**Comment by alextea** [comment]
Yes, that was the intention. :+1:

**Comment by GeorgeGoodall** [comment]
Hey @alextea 
I've change the error summary header to show the new grouped message where appropriate. but what should we do about each individual item in the error summary? 

![Image](https://github.com/user-attachments/assets/6eed90ba-dc70-4124-8ecd-48aba6e2bc8a)

should we just remove the error summary and have the message instead? or maybe the error summary with a title of There is a problem and a single item of the grouped issue message? (seen in the example bellow)

![Image](https://github.com/user-attachments/assets/5844518d-4793-414f-8169-b2ed8273be10)

cc: @CharliePatterson

**Comment by alextea** [comment]
We should go with the second example.

The text should read:

## There is a problem
reference column must have unique entries

**Comment by GeorgeGoodall** [comment]
following discussions with alex, charlie and dilwoar. we have decided for now to further split down the tasks by field type. 

for example:
- with a datafile with 220 rows

instead of the task: 
you have 221 missing values

you might see the tasks
all you're start dates are missing
you have 1 row with a missing end date
