### ISSUE TITLE
Comms plan for launching MVS

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#308]
## Context:

- We're launching the minimum viable service for data providers, to support them in the process of submitting and updating their housing and planning data.
- Once this is live, we need to communicate this launch to all the LPAs who've been involved in the program thus far, so that they can start using the new service.

## Acceptance criteria:

- As an LPA involved in the ODP program, when the minimum viable service is launched, I am aware of what it's for and how to access and use it, and how to share any feedback I have.

## Tasks:
- Design short term approach to inform ODP LPAs that we're launching the service
- LPAs may be shocked at the status of their data, so how might we mitigate against that

**Comment by MJFaucherFolie** [comment]
Drafted plan: https://docs.google.com/document/d/1XZwkQL6W-JdSwiXDVZJffDhCCCq1Hh3wggNuRhefsxI/edit

Shared with Gwen to have a brief review if she has time 🤞

**Comment by MJFaucherFolie** [comment]
Gwen has provided feedback and I've actioned it.

Will share with Charlie for input

**Comment by Darren-CheckPlanningData** [comment]
Blocked due to pushback from community managers not wanting to share email addresses for LPAs.
MJ looking to set up a discussion with Tom (Community manager), Charlie & Steve to resolve the concerns.
