### ISSUE TITLE
Bug: On 'live' datasets, the link to "View the dataset on on the planning data platform" links to a brownfield land dataset 

### ISSUE THREAD

**Issue by jimmytidey** [digital-land/submit#321]
### ** Steps to reproduce ** 
Go to: https://check.planning.data.gov.uk/organisations/local-authority:BNE/article-4-direction
Click "View the dataset on the Planning Data platform"  

** Observed behaviour ** 
Clicking "View the dataset on the Planning Data platform"  takes you to this page: 
https://www.planning.data.gov.uk/entity/?dataset=brownfield-land&geometry_curie=statistical-geography:E07000091

** Expected behaviour ** 
Link takes you to a map showing A4 directions for Barnet  

**Another instance of this issue reported by user:**
Steve Messer
  27/08 at 11:00 AM
Hello! Possibly a small bug. When you click the ‘View this dataset on the platform’ link, it’s taking this user through to the wrong page.
Probably needs a small test around it to make sure the correct URL is provided in the hyperlink?

Tim Rodaway
Apparently we've got 'Article 4 direction area' already live, however when you click through on the links you get New Forest's Brownfield dataset.
https://check.planning.data.gov.uk/organisations/local-authority:NBL
https://check.planning.data.gov.uk/organisations/local-authority:NBL/article-4-direction-area
https://www.planning.data.gov.uk/entity/?dataset=brownfield-land&geometry_curie=statistical-geography:E07000091

![image](https://github.com/user-attachments/assets/69d74861-e8b6-4901-a87a-6ca40995913e)

From MHCLG | 27/08 at 10:41 AM

**Comment by DilwoarH** [comment]
PR raised: https://github.com/digital-land/submit/pull/347

**Comment by CharliePatterson** [comment]
Are these changes live? I just checked their article 4 direction area page, and it's still pointing to the brownfield land search results: https://check.planning.data.gov.uk/organisations/local-authority:NBL/article-4-direction-area

**Comment by DilwoarH** [comment]
> Are these changes live? I just checked their article 4 direction area page, and it's still pointing to the brownfield land search results: https://check.planning.data.gov.uk/organisations/local-authority:NBL/article-4-direction-area

It doesn't look like the changes are live, do we have something that shows us which PRs are live?
