### ISSUE TITLE
Remove submit link from http error page

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit#346]
# Problem Statement
the submit service isn't live and should be hidden, however we are currently linking to it from the http error page

![Image](https://github.com/user-attachments/assets/0b2388c8-a253-40d7-b54c-7da16bbcdc24)

# Tech approach
Remove this link and simple link to the tech guidance

**Comment by DilwoarH** [comment]
is this a duplicate of #351 ?
