### ISSUE TITLE
Organisation dashboard: Content and design fixes

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#354]
## Organisation dashboard

![Image](https://github.com/user-attachments/assets/e91e89c2-4472-4fb1-82c5-3592361bcfeb)
![Image](https://github.com/user-attachments/assets/5887ae08-5f8c-4149-8fa8-7af93b8e242a)

- [x] Org name in breadcrumb needs correct capitalisation
- [x] Dataset list should be alphabetically ordered
- [x] "Not submitted" tag should be grey
- [ ] "Live" tag shows alongside text showing issues exist / either the tag or the text is wrong
- [x] When there's only a single issue the text should be "There is 1 issue in this dataset"

**Comment by DilwoarH** [comment]
Regarding:
```
 "Live" tag shows alongside text showing issues exist / either the tag or the text is wrong
```

This is the logic that sets the status:

```
   when (rle.status is null) then 'Not Submitted'
      when (rle.status != '200') then 'Error'
      when (it.severity = 'error') then 'Needs fixing'
      when (it.severity = 'warning') then 'Warning'
      else 'Live'
```

So if it has a status of`200` and has no severity then it's **Live**.
