### ISSUE TITLE
Header: Content and design fixes

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#358]
## Header

- [ ] GOV.UK logo and service title should link to `/manage` (needs fixing site wide)

![Image](https://github.com/user-attachments/assets/7cea5bca-c0f1-4244-9d7e-052de451c2a1)

**Comment by rosado** [comment]
We don't have a '/manage' route. Did you mean '/' @CharliePatterson ?

**Comment by CharliePatterson** [comment]
Ah - that route will disappear once we roll out the redirects, etc.? Then, yup, back to the start page at `/`
