### ISSUE TITLE
Don't show warning level errors on the dashboard or tasklist pages

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#359]
## Context

- The organisation dashboard is currently pulling through issues with severity level 'warning' - i.e. things that we've transformed or patched in the data.
- These are being treated the same way as all other issue types, and so the UI is asking LPAs to 'fix' the issues.
- However, we shouldn't be expecting them to change their data as a result of us patching or transforming it. Instead, we should be telling them why something is different.

## Acceptance criteria:

- Hide issues of severity level 'warning' from the dashboard and the dataset issues tasklist pages.

**Comment by rosado** [comment]
What does exactly hiding means in the above? @CharliePatterson  I imagine we don't actually want to hide the row from the overview page?

![Image](https://github.com/user-attachments/assets/a8f3bf67-5006-444a-a1d0-6c7a95b957b1)

**Comment by CharliePatterson** [comment]
Sorry for the confusion @rosado - there are various types of issues, and 'severity' is one of columns: https://datasette.planning.data.gov.uk/digital-land/issue_type

We don't want to be pulling through issue tags for issues categorised as 'warning' in the severity column.

**Comment by rosado** [comment]
So here's how the overview page and the task list page look after the update (arrows point to things that we would currently display as warning). Can you confirm that's how it should look like? @CharliePatterson 

### Overview page
![Image](https://github.com/user-attachments/assets/bbeaae8f-ead1-4248-bf16-938c178ab7a5)

### Task list page
![Image](https://github.com/user-attachments/assets/09bfd202-bb99-4c0e-b5d1-3ade7a4b06f6)
