### ISSUE TITLE
Spike: Gap Analysis of Alpha products

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#363]
Problem statement
- We have received a request to take inspiration of previous work developed during the alpha
- We need to conduct a gap analysis of what is currently live vs products and experiments conducted during the alpha
- The insight gathered will help us improve the service and build upon research conducted previously

Approach
- Review of the current and planned iteration of the service, as well as a comparison between products developed during the alpha

Acceptance criteria
- Understanding of products developed during the alpha
- Comparison of features between products developed during the alpha and the current service

Links:
https://www.gov.uk/service-standard-reports/digital-land-alpha-assessment-report
https://design.digital-land.info/
https://docs.google.com/document/d/1dsRrcHi43jl-_I_wnzmH0xVshl7-81cgF9sSo1hy3to/edit#heading=h.lqsnm9tu3ujj

**Comment by MJFaucherFolie** [comment]
Started drafting a spreadsheet to analyse the gaps between our service and the alpha prototypes: https://docs.google.com/spreadsheets/d/10o9Ojmt1kyZpXA7bNPIqpwMyObgWq1PY9Sjujr7Rudo/edit?gid=1358031272#gid=1358031272

**Comment by MJFaucherFolie** [comment]
Feedback highlighted to use a different medium, so moved gap analysis to doc: https://docs.google.com/document/d/1mWDMaK6LGgPZMq7FESvmUf0FC6MOPSoqMO2atVLKR10/edit

**Comment by CharliePatterson** [comment]
Looks great, thanks MJ 🙌
