### ISSUE TITLE
Bug: Buckinghamshire link not accepted in Check

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#373]
**What were you expecting to see:**
The Check application to accept the URL and review the data

**What are you seeing:**
An error on Check preventing the data on the link from being reviewed (screenshot of error attached)

![Image](https://github.com/user-attachments/assets/7373050c-6888-4ae0-8e34-16371cf9b05e)

**Who raised it:**
Buckinghamshire 
Swati & Data Management team

**Problem causing:**
Preventing the Data Management team from confirming if changes made to the data conform with our data standards.

**Links:**
The URLs in question: 
- https://maps.buckinghamshire.gov.uk/server/services/Planning/TPOs/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetCapabilities

**Extra info**
Resolved similar issue with [Southwark](https://github.com/orgs/digital-land/projects/7/views/9?filterQuery=Bug%3A+Check+service+refusing+URL+for+static+file&pane=issue&itemId=72878387)

**Comment by rosado** [comment]
Firing a HEAD request via curl results in 500 error. But straight GET works OK. Passing extra `User-Agent` header has no effect, so the fix from  #183 won't work for this

`curl -I "https://maps.buckinghamshire.gov.uk/server/services/Planning/TPOs/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetCapabilities"`

**Comment by MJFaucherFolie** [comment]
This endpoint is referenced in ticket #608 

Closing this _duplicate_ ticket
