### ISSUE TITLE
Streamline & improve the check tool user experience

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#384]
## Context:

We have identified a number of opportunities to streamline and improve the user experience of the check tool:

- **Removing the start page:** This is now redundant, as people should have sufficient context from the previous page in the journey. Additionally, users rarely read start pages, making them extra redundant.
- **Deep-linking:** Given the new user journey, the second step in the flow of the check tool is also now redundant, as it's an unnecessary step, since they would've arrived on the tool via a specific dataset page.
- **Completion page:** The current experience at the end of the check tool flow tells the user to publish their data and then email the endpoint URL to us. This needs to connect to the rest of the user journey.
- **Context throughout experience:** As the user navigates through the tool, there's no context to tell them which dataset they're checking.

## Design tasks, questions & considerations:

- Consider the holistic user journey and potential implications of these things (in particular the first two): Are there any scenarios where this might prevent a problem? What do we do in instances where the user has bookmarked the link?
- Do we want to maintain two separate versions of the tool? One standalone one, and a second that's baked into the dashboard/service flow?
- How much of a pain is it going to be for a user to check multiple files? (is this standard behaviour currently?)
- What do we need to change on the completion page?
- How do we add the necessary context to help the user understand where they are? Is there any other context we need to provide - e.g. where they are in the process of checking their content (progress indicator)?

On removing the start page:

- Is this just a simple case of removing the start page? Or are there other scenarios that we might have to account for?
- Do we need to update the content on the 'step-by-step' page too, to add any of the context provided on the start page? Or does that already set the right expectations?
- Do we need to complete https://github.com/digital-land/submit.planning.data.gov.uk/issues/307 first?

**Comment by maddie-broxup** [comment]
Alex and I ran through some content design iterations yesterday, [which are in this Mural board](https://app.mural.co/t/tpximpact0584/m/tpximpact0584/1728471779032/10f7551ffb29a0c520676d505cba887c1ae5518e?sender=uabf43dfc77286c37c4938171).

Alex is working on updating the prototype to reflect those.

**Comment by alextea** [comment]
<img width="1920" alt="Check tool integration flow" src="https://github.com/user-attachments/assets/5228df83-ccf2-4f6c-9aea-a3bf61c42aa3">

**Comment by alextea** [comment]
[Dataset details page with "Check dataset" link](https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/overview/v2/local-authority:LBH/dataset/article-4-direction)

[Check flow](https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/check/local-authority:LBH/article-4-direction/choose-upload)
