### ISSUE TITLE
Spike: what to do when we making queries that return more than 1k rows

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit#400]
# Problem statement

Datasette currently limits responses to 1k rows. 
this causes problems for example on the issues page. when we have more than 1k issues. i.e.: on this [page](https://submit.staging.digital-land.info/organisations/local-authority:LBH/tree-preservation-order/reference%20values%20are%20not%20unique/5

clicking on any pagination link above 1k causes the page to crash, because we don't have the entity number for the entity that that page is referring to

## Impact

**How many people are affected** (04/11/2024)
- The [datasette has highlighted ](https://datasette.planning.data.gov.uk/performance?sql=SELECT+%0D%0A++++organisation%2C%0D%0A++++organisation_name%2C%0D%0A++++dataset%2C%0D%0A++++SUM%28count_issue_error_internal%29+AS+total_error_internal%2C%0D%0A++++SUM%28count_issue_error_external%29+AS+total_error_external%2C%0D%0A++++SUM%28count_issue_warning_internal%29+AS+total_warning_internal%2C%0D%0A++++SUM%28count_issue_warning_external%29+AS+total_warning_external%2C%0D%0A++++SUM%28count_issue_notice_internal%29+AS+total_notice_internal%2C%0D%0A++++SUM%28count_issue_notice_external%29+AS+total_notice_external%2C%0D%0A++++%28SUM%28count_issue_error_internal%29+%2B+%0D%0A+++++SUM%28count_issue_error_external%29+%2B+%0D%0A+++++SUM%28count_issue_warning_internal%29+%2B+%0D%0A+++++SUM%28count_issue_warning_external%29+%2B+%0D%0A+++++SUM%28count_issue_notice_internal%29+%2B+%0D%0A+++++SUM%28count_issue_notice_external%29%29+AS+total_issues%0D%0AFROM+%0D%0A++++provision_summary%0D%0AWHERE+%0D%0A++++dataset+IN+%28%27article-4-direction%27%2C+%27article-4-direction-area%27%2C+%27conservation-area%27%2C+%0D%0A++++++++++++++++%27conservation-area-document%27%2C+%27listed-building-outline%27%2C+%27tree%27%2C+%0D%0A++++++++++++++++%27tree-preservation-order%27%2C+%27tree-preservation-zone%27%29%0D%0AGROUP+BY+%0D%0A++++organisation%2C+organisation_name%2C+dataset%0D%0AHAVING+%0D%0A++++total_issues+%3E+1%0D%0AORDER+BY+%0D%0A++++organisation%2C+total_issues+DESC%3B%0D%0A)that there are 13 LPAs who have more than 1k issues

What part of the process is it impacting
- Review the issues impacting data

Is it preventing people from completing an action or a minor annoyance 
- It is a minor annoyance on the dashboard, as people may not go through all paginated pages to understand all the issues

**Comment by CharliePatterson** [comment]
Limited options until we have an API in place to handle this - need to work with Infra to figure out the requirements for the API and to put in place a plan for migrating the service from Datasette to the API.
