### ISSUE TITLE
Filter out internal issues

### ISSUE THREAD

**Issue by GeorgeGoodall** [digital-land/submit#401]
# Problem statement

We are currently showing internal and external issues, we should only be showing external issues

## Bonus task

the '[unknown entity - missing reference](https://datasette.planning.data.gov.uk/digital-land/issue_type/unknown+entity+-+missing+reference)' issue is labeled as external. but this is an internal issue. we should have data standards change this

**Comment by CharliePatterson** [comment]
The work to filter out internal issues was completed elsewhere. The second piece around the `unknown entity - missing reference` issue needs a bit more investigation to determine the right approach.
