### ISSUE TITLE
Table view for displaying dataset issues

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#406]
## Context:

- The current implementation of the dataset issues page is that we're playing issues back to users on a per-entity / per-record basis, meaning that users have to click through each entity/record to view the details of the issue.
- This isn't a great user experience when the user is faced with a high volume of issues.
- A better experience would be to display this data back to them in an aggregated format, in a table.

## Acceptance criteria:

- As a data provider, when I'm viewing the dataset issues page, I can view the issues presented in a table in an aggregate view.

## Implementation details:

- The intention is to re-use the component from the check tool, so that we don't have multiple versions of the same thing floating around, and only have to maintain styles in one place.
- However, we'll first need to break this out into a separate component.

## Questions/considerations for refinement:

- Should we update the styling of the table in a separate ticket, and make the focus of this one about getting the table into the issues details page? **Yes**
- @alextea I think there's a need to map out the interaction here between how users get from the per-entity view to the table view, unless you've already covered this? - **table view will come first. Interaction map still needed**
- Assumption to check: the table would only show records that contain issues, rather than the full dataset? **Thats the right direction**
- Does the table show all available columns? **Yes**
- Is there a pre-set ordering to the columns? **No, but possible** e.g. new sorting/priority column (work for Infra)
- A future iteration on this could be to enable users to select a record from the table and change the map to display the geospatial data for that record. This is out of scope for this iteration. **Future enhancement**

**Comment by alextea** [comment]
I think for this first iteration we can add a back link above the issue summary:

![Image](https://github.com/user-attachments/assets/bcf79ff7-4306-4eee-ab4d-ff00f1b57362)

**Comment by CharliePatterson** [comment]
Thanks @alextea 🙏 just to clarify:

- The table view will be the default
- To navigate back to the table view from the entity-level view, we will use a back link above the summary

Questions:

- How does the user navigate from the table view to the entity-level view?
- Is the table view the same as entity-level, except that the entity table is replaced with the aggregated table?

**Comment by alextea** [comment]
> How does the user navigate from the table view to the entity-level view?

The reference column (which should appear in the first position) should contain a link to the entity-level view

> Is the table view the same as entity-level, except that the entity table is replaced with the aggregated table?

Yes. Each view should have their own pagination as well (table view might not always need it shown if all rows fit on a single page)

**Comment by alextea** [comment]
> Is there a pre-set ordering to the columns? No, but possible e.g. new sorting/priority column (work for Infra)

I think reference should show first, the rest should be in alphabetical order for now

**Comment by CharliePatterson** [comment]
I've broken this out into three tickets as per yesterday's discussion, and encapsulated them in this epic: https://github.com/digital-land/submit/issues/424
