### ISSUE TITLE
Dataset details summary table

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#407]
## Context:

- When data providers have submitted their datasets, they will want to know that it has been indexed correctly by the platform, and will want to check a number of factors.
- To enable this, we want to play back a summary/overview of key information about their data to them.

## Acceptance criteria:

As a data provider, when I'm viewing the dataset details page, I can view a summary of the dataset I'm viewing, so that I can check whether the data we've submitted is:

- Correct
- Complete or whether we need to improve the quality of it
- Up-to-date

This includes the following information:

- Number of records
- Number of fields supplied
- Number of fields matched
- Licence
- Source documentation URL
- Data URL
- When the data URL was last accessed
- When the data URL was last updated

@DilwoarH to investigate which of these points can be easily obtained. Any that are more difficult can be deprioritised.

## Designs:

![Image](https://github.com/user-attachments/assets/ade531a6-b021-473c-a1cd-17c7b77ca951)

**Comment by DilwoarH** [comment]
Summary of changes needed:
- Support multiple resources
- The count for fields supplied is incorrect (need to be the same as https://config-manager-prototype.herokuapp.com/reporting/odp-summary/conformance)
- The count for records needs to be combined with the number of entities for all resources

**Comment by DilwoarH** [comment]
Design ref: https://github.com/digital-land/submit/issues/311#issuecomment-2331673999

**Comment by DilwoarH** [comment]
Ref to code where the conformance table is 

[application/templates/reporting/odp_conformance_summary.html](https://github.com/digital-land/config-manager/blob/d62976f0465b015e7ddb821052b7681b199728cc/application/templates/reporting/odp_conformance_summary.html)

**Comment by DilwoarH** [comment]
@CharliePatterson - handed this over to @GeorgeGoodall-GovUk to finish off

**Comment by CharliePatterson** [comment]
@DilwoarH @GeorgeGoodall-GovUk is there anything outstanding on this, or is it good to go live?
