### ISSUE TITLE
Navigation between dataset pages

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#408]
## Context:

- The current flow between the dataset details page, the tasklist, and issues pages is disjointed. A better user experience would be to enable users to more easily switch back and forth between those pages.

## Flow diagram:

The second flow here shows the interaction between these pages:

![image](https://github.com/user-attachments/assets/cb1685a7-eea1-4afe-8f1e-4882c8210861)

## Designs:

- Pending: https://github.com/digital-land/submit/issues/311

**Comment by alextea** [comment]
<img width="1250" alt="Dataset details release iterations" src="https://github.com/user-attachments/assets/03a22f6d-6468-46c4-a488-a3201d0ccb5a">
