### ISSUE TITLE
Content design review for issue messages

### ISSUE THREAD

**Issue by GeorgeGoodall-GovUk** [digital-land/submit#411]
# Problem statement

Our issue messages could use a bit of love

# Considerations

issues can be discriminated by...
- issue type
- issue field
- issue count

Issues may also present different in different parts of the application such as in the error summary heading, an error summary item, the issue table, or an entity view

### currently the content for these issues are stored here: https://github.com/digital-land/submit/tree/main/src/content

we have a number of tokens that can be used in these issue messages including
- {num_entries}
- {num_issues} (same as num entries)
- {column_name}

**Comment by alextea** [comment]
Have made some changes in https://github.com/digital-land/submit/tree/issue-message-review — need to discuss where the messages appear, especially the entityIssuesMessages as I'm not sure they make sense now.

Will also need to review issue messages that appear in the table/entity view as these need to be different.

**Comment by alextea** [comment]
Closing this in favour of #441
