### ISSUE TITLE
Update column-level error messages

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#441]
## Context:

- We recently updated the way that column-level issues are displayed (as per: https://github.com/digital-land/submit/issues/306).
- However, we aren't pulling through the user-friendly error messages, as specified here: https://github.com/digital-land/submit/issues/306#issuecomment-2318216022

---

## User-friendly error messages for column-level issues:

I have collated a [list of error messages in this spreadsheet](https://docs.google.com/spreadsheets/d/1hvffB4LuHEHR2WutAxp98CzG0WsZJFlx-2VmGeIM5Yk/edit?gid=813787384#gid=813787384) (under the heading "column level errors")

error type | message
-- | --
column not supplied | `column-name` column is missing
all rows are empty | `column-name` column is missing values
all rows are invalid date | `column-name` column must be in YYYY-MM-DD format
all rows are invalid coordinates | `column-name` column must have valid coordinates
all rows are invalid decimal | `column-name` column must have decimal numbers
all rows are invalid integer | `column-name` column must have valid integers
all rows are too small | `column-name` column must be above the minimum number needed
all rows are too large | `column-name` column must be below the maximum number needed
all rows are invalid flag | `column-name` column must have valid YES or NO values
all rows are invalid URI | `column-name` column must have valid URIs
all rows are invalid WKT | `column-name` column must have valid WKT values
all rows are future entry-date | `column-name` column must be in the past
all rows are WGS84 out of bounds | `column-name` column is WGS84 out of bounds
all rows are invalid geometry - not fixable | `column-name` column must have valid geometry
all rows are Unexpected geom type | `column-name` column must have valid geometry
all rows are Unexpected geom type within GeometryCollection | `column-name` column must have valid geometry
all rows are WGS84 out of bounds of England | `column-name` column must be within England
all rows are WGS84 out of bounds of custom boundary | `column-name` column must be within the specified boundary
all rows are OSGB out of bounds of England | `column-name` column must be within England
all rows are OSGB out of bounds of custom boundary | `column-name` column must be within the specified boundary
reference values are not unique | `column-name` column must have unique entries

**Comment by rosado** [comment]
Those new messages are better, but they're almost not grammatically correct. Maybe we could rephrase them a bit (see table below, I added an `updated?` column to mark which messages I think we should update).

error type | updated?|message
-- | --|--
column not supplied || `column-name` column is missing
all rows are empty || `column-name` column is missing values
all rows are invalid date || `column-name` column must be in YYYY-MM-DD format
all rows are invalid coordinates || `column-name` column must have valid coordinates
all rows are invalid decimal |yes|  values in `column-name` column must be decimal numbers
all rows are invalid integer | yes|values in `column-name` column must be valid integers
all rows are too small |yes| values in `column-name` column are too short
all rows are too large | yes|values in `column-name` column are too long
all rows are invalid flag | yes|values in `column-name` column must be `YES` or `NO`
all rows are invalid URI | |`column-name` column must have valid URIs
all rows are invalid WKT || `column-name` column must have valid WKT values
all rows are future entry-date |yes| date in the `column-name` column must be in the past
all rows are WGS84 out of bounds |yes| values in the `column-name` column is WGS84 out of bounds
all rows are invalid geometry - not fixable|yes| values in the `column-name` column must be a valid geometry
all rows are Unexpected geom type |yes| values in the `column-name` column must be a valid geometry
all rows are Unexpected geom type within GeometryCollection |yes| values in the `column-name` column must be a valid geometry
all rows are WGS84 out of bounds of England |yes| values in the `column-name` column must be within England
all rows are WGS84 out of bounds of custom boundary |yes| values in the `column-name` column must be within the specified boundary
all rows are OSGB out of bounds of England |yes| values in the `column-name` column must be within England
all rows are OSGB out of bounds of custom boundary |yes| values in the `column-name` column must be within the specified boundary
reference values are not unique |yes| values in the `column-name` column must be unique

**Comment by alextea** [comment]
I think this ticket duplicates #411 — @gwencariad and I will review the issue messages

**Comment by alextea** [comment]
Comment from #411

**Have made some changes in https://github.com/digital-land/submit/tree/issue-message-review — need to discuss where the messages appear, especially the entityIssuesMessages as I'm not sure they make sense now.

Will also need to review issue messages that appear in the table/entity view as these need to be different.**

**Comment by alextea** [comment]
@maddie-broxup and I reviewed the messages with @GeorgeGoodall-GovUk — the entity level messages are not needed. The up to date messages are in the https://github.com/digital-land/submit/tree/issue-message-review branch
