### ISSUE TITLE
Implement GeoJSON Layers on map view

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#444]
## Context:

- Certain datasets are quite large, and datasette times out after a certain amount of time, leading to the page to not load.
- As an interim solution, we've wired it up so that the tree datasets load the old version of the dataset details page rather than the new one.
- To enable us to route users to the page with the better user experience, we should implement GeoJSON Layers on the map view.

## Technical implementation:

-

**Comment by DilwoarH** [comment]
PR raised: https://github.com/digital-land/submit/pull/453
