### ISSUE TITLE
Bug: Map on Check defaults to London

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#449]
## Issue:

- We've enabled maps to display when users are checking their data, but the map will default to London:

![Image](https://github.com/user-attachments/assets/18263281-4b84-4abe-8608-78685f93c02b)

## Who raised it
MJ & LPA via Jira

## Problem causing
LPAs, such as New Forest NPA are unable to see their data visualised on a map prior to submission.

## Tasks:
- [ ] Investigate why this occurs
- [ ] Agree the right approach 

## Example:
https://submit.planning.data.gov.uk/check/results/oXLy83RBDzUtMzUGmrfdy6/0

**Comment by DilwoarH** [comment]
@MJFaucherFolie - can you give the URL you used to create the example please?

**Comment by MJFaucherFolie** [comment]
> @MJFaucherFolie - can you give the URL you used to create the example please?

Hey Dilwoar! Here is the link - https://submit.planning.data.gov.uk/check/results/oXLy83RBDzUtMzUGmrfdy6/0

**Comment by DilwoarH** [comment]
> > @MJFaucherFolie - can you give the URL you used to create the example please?
> 
> Hey Dilwoar! Here is the link - https://submit.planning.data.gov.uk/check/results/oXLy83RBDzUtMzUGmrfdy6/0

Sorry should have been clear - I meant the CSV/GeoJSON or URL for the source

**Comment by neilfwar** [comment]
@DilwoarH @MJ what was the outcome of the bug fix ? ie what was done?

**Comment by GeorgeGoodall-GovUk** [comment]
We are still seeing this happen.
Here’s an example: https://submit.planning.data.gov.uk/check/results/S9KfzRorj6htq2CE4vr5FM/0
Source data: https://www.highpeak.gov.uk/media/4893/Brownfield-Land-Register-2023-CSV/Excel/5chp23.brownfield-land_register.csv?m=1703059825267

**Comment by DilwoarH** [comment]
This was caused by invalid WKT data.

Invalid formats such as `POINT ( -1.909243  53.264474)` where it should be `POINT (-1.909243  53.264474)` could break the map.

A PR has been raised to ensure invalid points are not added to the map but should this be raised as an error by the request API?

cc @GeorgeGoodall-GovUk @MJFaucherFolie @alextea @CharliePatterson
