### ISSUE TITLE
Bug: Error reviewing URL on Check

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#450]
## What were you expecting to see:

The Submit tool accept the URL and proceed to review the data on it

## What are you seeing:

![Image](https://github.com/user-attachments/assets/f638903e-6517-4378-8a00-40a8dbe7eeff)

## Who raised it
MJ

## Problem causing
Leicester are unable to review issues related to their dataset

## Steps to replicate:

- Try and process this Conversation Area endpoint via Check: https://geoserver.leicester.gov.uk/geoserver/CONSAREAS/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=CONSAREAS%3AODP_CONSAREAS&maxFeatures=50&outputFormat=application%2Fjson

## Additional info
- Downloading their data and [processing it via Check works fine](https://submit.planning.data.gov.uk/check/results/NXdMeovuZgPiPNK678JuQN/0). Their data is below the 100mb limit.
- Can we check what meta we are receiving from the server as this could be the issue

## Tasks:
[ ] Investigate why this occurs

**Comment by MJFaucherFolie** [comment]
[conservation area download.json](https://github.com/user-attachments/files/17030698/conservation.area.download.json)

^ this is a download of their data, which I used to check if their data was over the size limit. It is below the limit and the data itself has no issues

**Comment by DilwoarH** [comment]
The problem was that specific URL was not returning a `content-length` header. This meant that the comparison between the length of the file and max length was being compared to a undefined file length.

I am raising a PR to just return true if no file length is passed in - the checks in the API should stop anything malicious.
