### ISSUE TITLE
Spike: Testing

### ISSUE THREAD

**Issue by DilwoarH** [digital-land/submit#455]
## Description
We need to conduct a 1-day spike to explore and identify the best testing strategies for our Submit repo. The goal is to gather enough information to make informed decisions about our testing approach, which will help improve code quality and ensure reliable functionality in our Express.js application.

## Goals
- Review the current testing setup in the repository, including any existing tests for the Express.js routes and middleware.
- Explore testing frameworks and tools suitable for a Node.js and Express.js project (e.g., Mocha, Chai, Jest, Supertest). Potentially standardising with one or two libraries.
- Evaluate the feasibility of implementing these strategies within our codebase, focusing on unit testing, integration testing, and end-to-end testing for Express.js.
- Investigate best practices for testing Express.js applications, such as mocking, stubbing, and using in-memory databases.
- Document the findings, including pros, cons, and any potential challenges.
- Provide recommendations on the next steps for implementing the chosen testing strategies.

## Deliverables
- A brief report summarising the findings of the spike.
- Recommendations for testing frameworks/tools to use with Node.js and Express.js.
- A plan outlining the steps for integrating the chosen testing strategy into our development workflow.

## Timebox
- This spike is limited to 1 day of investigation and documentation.

## Acceptance Criteria
- A document or markdown file added to the repository with the findings and recommendations.
- A short presentation or summary to the team outlining the results of the spike.

**Comment by CharliePatterson** [comment]
We will have an OKR for Q3 relating to this: something around better monitoring and testing capabilities, to ensure the stability and scalability of the platform and to capture issues before users spot them. It would be good to consider this spike in light of this - i.e. to make more concrete recommendations about the specific things we should be tackling in Q3 as part of this objective.

**Comment by rosado** [comment]
I'd like to focus on integration testing, as we've been working on refactoring our code to make actual unit testing possible (e.g. not requiring us to create a bunch of mock objects before we can test).

We can get a lot of value by using [Hurl](https://hurl.dev/). The cost of introducing it is not high, as Hurl is just one command line too and syntax of Hurl scripts is very close to what HTTP looks over the wire (see the example below, borrowed from Hurl's website).

```
# Access the home page
GET https://example.org
HTTP 200
[Captures]
csrf_token: xpath "string(//meta[@name='_csrf_token']/@content)"

# Do login!
POST https://example.org/login?user=toto&password={{password}}
X-CSRF-TOKEN: {{csrf_token}}
HTTP 302
```

See more examples on the Hurl homepage/docs.

By using Hurl, you get:
- easy and readable way of specifying client/server exchanges, 
- executable documentation (that you can include in your test suite)
- a way to document repro steps for bugs (and as mentioned above: they're executable)

I've worked on integrating Hurl into a project in the past and we can "borrow" the whole setup and drop it in. See the [documentation](https://github.com/Swirrl/datahost-prototypes/blob/41688872bc4987d856b0cc55542a8b23aacd8e76/datahost-ld-openapi/doc/integration-testing.md) to get an idea. 

The only pieces of work needed to have something running:
- port the script for running Hurl scripts to bash or JS (1-2 hours of work max)
- update CI/CD setup to run it against a container, but also a deployed service

**Comment by DilwoarH** [comment]
# Automated Testing Report

This report reviews the use of automated testing we currently have on the submit service and suggest what improvements can be made.

What is automated testing?
--------------------------

Automated testing refers to the use of software tools to execute predefined test cases on an application, system, or component to ensure it functions as expected. Unlike manual testing, where a human tester runs tests by hand, automated testing relies on scripts and specialised testing frameworks to perform the tests, report results, and compare the actual output with the expected output.

Here are some key aspects of automated testing:

#### 1 - Automation Tools

Automated testing is driven by tools like Selenium, JUnit, TestNG, Cucumber, Appium, and many others. These tools allow you to write test scripts that can simulate user interactions, validate results, and report issues.

#### 2 - Types of Automated Tests

-   Unit Testing: This tests individual components or units of the code (like functions or methods) in isolation. It focuses on verifying the smallest pieces of logic in the application.

-   Integration Testing: After unit testing, integration testing ensures that multiple modules or components work together as expected. It checks the interaction between different parts of the system (e.g., database interactions, API integrations).

-   Functional Testing: This type of testing verifies that the software behaves as specified in the requirements. It focuses on the system's functionality and ensures that the application's features work as intended.

-   End-to-End Testing: End-to-end testing simulates real-world scenarios by testing the application from the user's perspective, from start to finish. It ensures that the entire flow of the application works as expected, often including interactions with external systems like databases or third-party APIs.

-   Performance Testing: This includes testing the application's performance under different conditions, such as high load, stress, or a large number of simultaneous users. It helps identify bottlenecks and ensures the system is stable and responsive under stress.

-   Regression Testing: Whenever changes (like bug fixes or new features) are made to an application, regression tests ensure that the new changes do not break any previously working functionality. Automated regression tests can quickly check that everything continues to work properly after updates.

-   Acceptance Testing: User Acceptance Testing (UAT) is performed to ensure the software meets the business requirements and is ready for deployment. It is often conducted by business users, but automated acceptance tests are also possible. These tests simulate real-world scenarios based on the client or stakeholder's expectations and confirm whether the system behaves as expected in a production-like environment. Tools like Cucumber or Robot Framework allow you to write automated acceptance tests in a readable, business-friendly format (like Gherkin syntax) to verify that the software satisfies acceptance criteria.

#### 3 -  Test Execution

Automated tests are executed either manually (triggered by a user) or in an automated environment such as CI/CD pipelines (e.g., Jenkins, GitLab CI) where tests run automatically on every code change or build. This allows for continuous validation of the system.

#### 4 - Test Scripts

Testers or developers write scripts (code) to automate the testing process. These scripts typically mimic user interactions or service calls, check expected results, and log any failures.

#### 5 - Advantages of Automated Testing

-   Speed: Tests are executed much faster compared to manual testing.

-   Reusability: Once test scripts are written, they can be reused multiple times.

-   Consistency: Automated tests are more reliable since they don't suffer from human errors or fatigue.

-   Coverage: Automated testing allows for large-scale regression tests and increases test coverage.

-   Cost-Effective in the Long Run: While the initial setup cost can be high, automated testing saves time and money over repeated test cycles.

#### 6\. Disadvantages of Automated Testing

-   Initial Investment: It requires time and resources to set up automated testing frameworks.

-   Maintenance: Test scripts may need to be updated as the application evolves.

-   Not Suitable for Exploratory Testing: Automated tests are predefined and don't handle exploratory or ad-hoc testing scenarios well.

#### 7\. Use Cases

Automated testing is typically used in projects where:

-   The application undergoes frequent updates or has a long life cycle.

-   There's a need for repeated testing of the same functionality.

-   Complex applications that require extensive regression testing.

What do we currently have on the Submit application?
----------------------------------------------------

We currently have three types of testing that is covered on the platform:

-   Unit tests

-   Acceptance tests

-   Integration tests

### Coverage

1.  Unit tests

1.1.  57.58% Statements 3306/5741

1.2.  81.13% Branches 400/493

1.3.  62.67% Functions 136/217

1.4.  57.58% Lines 3306/5741

2.  Acceptance tests

2.1.  8 acceptance test

2.1.1.  Covering only the request check flow

3.  Integration tests

3.1.  32 tests

3.1.1.  Covers 4 sections and 32 scenario

Q3 Technical OKRs (related to testings)
---------------------------------------

#### Objective

Improve the scalability and stability of the technical platform

#### Key results

KR1.  Reduce the number of unhandled errors raised per month in Sentry by 95%, from 2672 to 134

KR2.  Achieve 95% automated unit test coverage, focusing on critical components and business logic

KR3.  Implement end-to-end tests for the top 5 most critical user journeys, covering both normal and edge-cases

KR4.  Reduce average application response time by 30% under peak load conditions

Suggested testing implementation
--------------------------------

1.  Increase coverage of unit tests to 95%

  1.1.  This will allow us to iterate at pace without worrying about breaking things

  1.2.  Continue to use ViTest as we already have 50% coverage and no significant value with moving to another package like Jest.

2.  Add a unit test coverage report for every PR

2.1.  [Vitest Coverage Report - Actions - GitHub Marketplace](https://github.com/marketplace/actions/vitest-coverage-report)

3.  Implement end to end tests using Playwright

  3.1.  Ensure end to end tests run on every PR raised against the preview app if possible

4.  Add pipeline to run end to end tests on merge, on staging and on production

4.1.  Ensure production tests do not write update anything

5.  Stretch: Add load testing to ensure application is able to handle high spikes in traffic
