### ISSUE TITLE
dataset details: do we need to change the documentation_urls and how they show

### ISSUE THREAD

**Issue by GeorgeGoodall-GovUk** [digital-land/submit#462]
# Problem statement
from what i can tell there a documentation_url that maps to every endpoint. but is this correct? should we be showing all of these? 

# Tasks
- [ ] find out the relationship between a provision [lpa, dataset], endpoint and a documentation_url (speak with owen)
- [ ] evaluate if the design need changing for the dataset details page
- [ ] implement

**Comment by alextea** [comment]
In my understanding there's a source documentation URL that LPAs are required to supply when they submit that has to be on their domain and contain a link to the source data. This is how we know data comes from an authoritative source.

In document datasets there also document urls for each entity that link to the relevant legal documents.
