### ISSUE TITLE
Limitations of Smartlook

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#465]
## Problem statement
Our analytics is reliant on Smartlook, but the tool is limited
We need to identify a different approach to ensure we have accurate metrics

## User story
As a... Service Owner of Planning Data
I need... To understand how the platform is being used
So that... I can assure Senior Stakeholders of the impact the project is making

## Acceptance criteria

- [x] Draft doc
- [x] Share with Charlie
- [ ] Action feedback / actions

**Comment by CharliePatterson** [comment]
GA inbound: https://github.com/digital-land/submit/issues/519
