### ISSUE TITLE
Dataset details page: Provision-level view table

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#482]
## Context:

- The dataset details page plays data back to LPAs, showing them their geospatial data on a map, and a summary table that shows an overview of the data they've provided.
- There's also a need to show LPAs a provision level view of the data they've provided (i.e. all of the data from the various endpoints from that organisation for the specific dataset).
- Future iterations of this page might include:
  - Displaying an interactive map of the geospatial data
  - Highlighting data quality issues
  - Displaying more/all rows of data
  - Entity level view to be in a separate iteration

## Acceptance criteria:

- As a data provider, when I'm viewing the dataset details page, I see a tab option to view the data. When I click on that, I am presented with a table that shows me the data for the resources I've submitted for that dataset.

## Implementation details:

- Re-use the table component from the check tool and dataset issues pages.
- Paginate the results so that it's performant.

## Child tickets
- Broken table styling off into a separate ticket #598

**Comment by DilwoarH** [comment]
Do we have any designs or rough wireframes of how we want to show this @alextea?

**Comment by CharliePatterson** [comment]
Designs pending: https://github.com/digital-land/submit/issues/494

**Comment by GeorgeGoodall-GovUk** [comment]
No design for this currently, but as we have all the component parts. I'll put them all together and Alex can review once he is back
