### ISSUE TITLE
Issues not displaying correctly on dashboard

### ISSUE THREAD

**Issue by alextea** [digital-land/submit#498]
![Image](https://github.com/user-attachments/assets/409cb61d-c19a-4845-bb46-910768319983)

Issues are not displaying on the dashboard.

[Canterbury City Council](https://submit.planning.data.gov.uk/organisations/local-authority:CAT)'s Article 4 direction area dataset has 1 issue, the dashboard says it is "Live"

## Impact
How many people are affected (04/11/2024)
- 2 LPAs ([West Berkshire](https://submit.planning.data.gov.uk/organisations/local-authority:WBK/listed-building/overview) Listed Building is "Live" when it has an issue / [Buckinghamshire Counci](https://submit.planning.data.gov.uk/organisations/local-authority:BUC/listed-building)l listed building is "live" when it has an issue")

What part of the process is it impacting
- Dashboard

Is it preventing people from completing an action or a minor annoyance
- Massive impact on data quality

**Comment by CharliePatterson** [comment]
Should be fixed when other changes go live.
