### ISSUE TITLE
Number of fields supplied and match count is 0

### ISSUE THREAD

**Issue by alextea** [digital-land/submit#501]
![Image](https://github.com/user-attachments/assets/6a64da5c-8ef8-48b6-883f-c1144c620f33)

The "Number of fields supplied" and "Number of fields matched" counts are 0.

https://submit.planning.data.gov.uk/organisations/local-authority:CAT/article-4-direction-area/overview

**Comment by CharliePatterson** [comment]
This should be fixed with: https://github.com/digital-land/submit/pull/504
