### ISSUE TITLE
Data URL hasn't been accessed since January 2024

### ISSUE THREAD

**Issue by alextea** [digital-land/submit#502]
![Image](https://github.com/user-attachments/assets/7c637df8-aa1a-40c6-aac4-06c25dc0512e)

The Data URL hasn't been accessed since January 2024 but there are no errors presenting for this end point.

Is the endpoint inactive? Maybe we should display a status for active/inactive endpoints?

**Comment by CharliePatterson** [comment]
This will be tackled in a different ticket to only show active endpoints
