### ISSUE TITLE
Outdated error messages being displayed on task list and issue pages

### ISSUE THREAD

**Issue by alextea** [digital-land/submit#503]
![Image](https://github.com/user-attachments/assets/4f98e727-3f29-40ac-8847-319784da1372)

![Image](https://github.com/user-attachments/assets/44b57d3b-ae87-4c66-8f74-9c3e7e6cddd3)

![Image](https://github.com/user-attachments/assets/d647435d-6f12-4dcc-906a-c5f90ae3a917)

The error messages displayed on the [task list](https://submit.planning.data.gov.uk/organisations/local-authority:CAT/article-4-direction-area) and [issues pages](https://submit.planning.data.gov.uk/organisations/local-authority:CAT/article-4-direction-area/invalid%20date/start-date) are out of date. Updated error messages have been supplied.

**Comment by MJFaucherFolie** [comment]
@alextea Can we confirm if this issue has been addressed?

Upon checking the links, the error messaging has been updated

![image](https://github.com/user-attachments/assets/eb74b9a7-9bd7-4000-8819-2a8db314f057)

![image](https://github.com/user-attachments/assets/5add4b75-b58e-4020-8d9b-3a231537b99a)

![image](https://github.com/user-attachments/assets/a07434c8-0f4d-48fb-ba0f-2bc6638c08ad)

**Comment by CharliePatterson** [comment]
Thanks @MJFaucherFolie - yup, this looks like it's been fixed.
