### ISSUE TITLE
Review error handling for (some) 400 responses from datasette

### ISSUE THREAD

**Issue by rosado** [digital-land/submit#509]
This ticket is added after issues caused by unexpected table name changes in datasette. 

The change caused responses to some of our requests (`fetchColumnSummary`) to return 400 error. Which in turn ended up displaying `errorPages/400` page to the user. 

We need to revisit:
- why this particular page was displayed (and not generic 500 error, for example, which seems sensible when 3rd party service makes a breaking change)
- how to change the error handling flow in such cases to display more informative error

**Comment by stevenjmesser** [comment]
The content on the error page can be designed by Maddie (not sure she’s been added to this project on GitHub yet?)

**Comment by rosado** [comment]
This has been fixed (mainly in #657, but other PRs might have touched error handling, too). 

I verified that if `fetchColumnSummary` datasette request fails with 400, we display a 500 error page.
