### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jimmytidey** [digital-land/submit#519]
**Overview** 
Google Analytics will allow us to gather quantitative measurements of user behaviour that we cannot access through logs or SmartLook. 

This is motivated by: 
* OKRs requiring us to measure traffic
* Analytics data could feed into user research  

@MJFaucherFolie has [detailed SmartLook's limitations here](https://docs.google.com/document/d/10Z8tMsEF4VtZDuD0t65jPFKJbYdDe25xhbGFWFvnK_Y/edit?usp=sharing)

**Tech approach** 
There is already a cookie acceptance bar on planning.data.gov.uk. 

**Acceptance Criteria** 
* Google Analytics is tracking users who accept cookies
* Google Analytics is not tracking users who reject cookies

**Comment by DilwoarH** [comment]
@jimmytidey @MJFaucherFolie - do we have the GA codes?

**Comment by MJFaucherFolie** [comment]
![image](https://github.com/user-attachments/assets/9543173e-7551-4450-a69f-cd11c4dc28fc)



<script async src="https://www.googletagmanager.com/gtag/js?id=G-F2H5SW06PZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F2H5SW06PZ');
</script>

**Comment by DilwoarH** [comment]
@MJFaucherFolie @CharliePatterson - we need to add some content to the cookies page - https://submit.planning.data.gov.uk/cookies

Here is an example from GOVUK: https://www.gov.uk/help/cookie-details
