### ISSUE TITLE
Code review and product sign off process

### ISSUE THREAD

**Issue by DilwoarH** [digital-land/submit#525]
## What

Propose an updated code review and product sign off process.

## Why

We want to implement a sign off process that allows product managers and designers to review any work before it gets released to production.

A sign off process will ensure any bugs and immediate issue can be resolved before a feature is released.

## Outputs of this issue

- A documented process to follow

**Comment by DilwoarH** [comment]
# Code Quality Process with Designer & Product Manager Sign-Off

## 1. Pre-Development Planning
- **Kickoff Meeting**:
  - Involve developers, designers, and product managers (PMs).
  - Define acceptance criteria, including design and business requirements.
  - Identify edge cases, potential blockers, and key areas to focus on.

## 2. Development Stage
- **Feature Branch Workflow**:
  - Develop each feature/bug fix in a separate branch (e.g., `feature/new-dashboard`).
  - Set up automated unit tests and code linting.

## 3. Continuous Integration (CI) & Preview Link Setup
- **CI/CD Pipeline**:
  - On push or PR creation, Heroku automatically builds and deploys the branch to a **Heroku Preview App**.
  - Example: `https://submit-pr-[PR_NUMBER].herokuapp.com`

  **Example CI Workflow**:
  - Developer pushes code to the feature branch.
  - Heroku CI pipeline deploys the code to a preview environment.
  - Automated tests (unit, integration, acceptance) run to ensure code quality.

## 4. Peer Code Review
- **Pull Request (PR)**:
  - Developers submit a PR from the feature branch to the `main` branch.
  - Peer code reviews focus on:
    - Correct implementation of the feature or bug fix.
    - Performance, security, and scalability of the code.
    - Adherence to coding standards (ESLint, Prettier, etc.).

## 5. Designer Sign-Off (via Heroku Preview Link)
- **Preview Link Sharing**:
  - Share the **Heroku Preview Link** with the designer in the PR comments or via Slack.
  - Designers review UI/UX changes using the preview environment.

  **Designer’s Checklist**:
  - Does the implementation match design specs (e.g., Figma)?
  - Are interactions, transitions, animations, and responsiveness correct?
  - Is the visual hierarchy consistent across screens?

- **Feedback & Approval**:
  - Designer approves the PR via comment or provides feedback for revisions.

  **Example Sign-Off Comment**:
  - “Design looks good. Approved!”

## 6. Product Manager Sign-Off (via Heroku Preview Link)
- **Preview Link for PMs**:
  - After designer approval, share the **same Heroku Preview Link** with the PM.
  - PM checks the feature against business requirements and product roadmap.

  **PM’s Checklist**:
  - Does the feature solve the intended business problem?
  - Is the user experience intuitive and efficient?
  - Does it meet the defined acceptance criteria?

- **Feedback & Approval**:
  - PM approves or requests changes via PR comments or task management tools.

  **Example Sign-Off Comment**:
  - “Feature meets all requirements. Approved for merge!”

## 7. Automated Testing (CI) & Sentry Integration
- **Automated Testing**:
  - After designer and PM approval, automated tests (unit, integration, acceptance) are triggered again.
  - Ensure all tests pass before merging into `main`.

- **Sentry Integration for Error Tracking**:
  - Monitor for errors or warnings in both the **preview environment** and **production** using Sentry.
  - Share significant Sentry logs in the PR for any necessary fixes.

  **Example**:
  - "Noticed a warning in Sentry logs on the preview app – let's investigate before moving forward."

## 8. Merge to Main Branch & Deployment
- After receiving approval from both the designer and PM, and passing all tests:
  - Merge the feature branch into the `main` branch.
  - **Github action** triggers **production deployment** upon a successful merge to `main`.

## 9. Post-Deployment Monitoring (Sentry)
- **Sentry Monitoring**:
  - Monitor errors and performance issues in the **production environment**.
  - Log any critical issues as hotfixes or new tickets for the next sprint.

- **Follow-Up with PM/Designer**:
  - Post-launch, share any critical Sentry alerts with the PM and designer.

## 10. Feedback & Retrospective
- Conduct a **retrospective** meeting after each sprint or major release:
  - Gather feedback from designers and PMs on the process.
  - Identify areas for improvement.
  - Update the workflow if necessary.

---

## Example Workflow
1. **Branch Name**: `feature/new-dashboard`
2. **Heroku Preview Link**: `https://submit-pr-[PR_NUMBER].herokuapp.com/`
3. **Designer Feedback**: 
   - Designer reviews the Heroku preview link, comments on PR: “UI looks good, approved.”
4. **PM Feedback**: 
   - PM reviews the Heroku preview link, comments on PR: “Meets business requirements, approved.”
5. **Automated Tests**: Run automatically after approvals.
6. **Merge to Main**: Code is merged and deployed to production.
7. **Sentry Monitoring**: No critical issues detected in Sentry.
8. **Follow-Up**: Post-deployment checks with Sentry, feedback loop in retrospective.

---

## Benefits of This Workflow
1. **Visibility for All Stakeholders**: Designers and PMs can review changes visually using Heroku’s preview links without needing local setups.
2. **Early Detection of Errors**: Sentry integration ensures errors are tracked both in staging and production.
3. **Continuous Feedback Loop**: Designer and PM feedback is incorporated early, reducing rework.
4. **Automated Safeguards**: CI pipelines, automated testing, and Sentry ensure that only high-quality code reaches production.

**Comment by DilwoarH** [comment]
@CharliePatterson - could you review this please?

**Comment by DilwoarH** [comment]
Additional automation request added here: https://github.com/digital-land/submit/issues/543

**Comment by rosado** [comment]
I find it useful to have the issue number in the branch name, for example: `bob/199-important-feature`. This allows to quickly gage how old the branch is (without looking at commit history) and get more information (by looking up the issue number in github/jira/whatever).

**Comment by DilwoarH** [comment]
> I find it useful to have the issue number in the branch name, for example: `bob/199-important-feature`. This allows to quickly gage how old the branch is (without looking at commit history) and get more information (by looking up the issue number in github/jira/whatever). 

Thats a great idea - I agree, will update

**Comment by DilwoarH** [comment]
Improvements:

- Add ready for release column
- Github release notes
- Add checklist to template for code, design and product sign off
