### ISSUE TITLE
Brownfield land: field designation (must provide/should provide)

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#541]
## Context:

- The check tool needs to know which fields should exist in the dataset it's running the checks against. If the fields don't exist in the dataset, then the check tool will reject the file and notify the user of the error.
- These are currently managed as a list of "mandatory" fields in the backend (NB: this hard-coded implementation should be changed in future - there's a discussion pending to address this).
- The Infrastructure team needs to know which of the fields for brownfield land datasets should be considered mandatory (ones LPAs must provide), versus which are not mandatory (those they should provide). See [this ticket](https://trello.com/c/otLeEOAv/3565-brownfield-land-mandatory-fields) in their backlog for more context.
- The table below is a proposal on the designation for each of the fields. The ones designated "Should provide" are [the ones that come after this point in the guidance](https://www.gov.uk/government/publications/brownfield-land-registers-data-standard/publish-your-brownfield-land-data#:~:text=If%20any%20of%20the%20following%20fields%20are%20unknown%20or%20unclear%20to%20your%20organisation%2C%20you%20can%20leave%20them%20blank%3A).
- The intention of this ticket is to get sign-off on this proposal.

## Field designation:

| Field                 | Must / Should provide |
| --------------------- | --------------------- |
| OrganisationURI       | Must provide          |
| SiteReference         | Must provide          |
| SiteNameAddress       | Must provide          |
| GeoY                  | Must provide          |
| GeoX                  | Must provide          |
| SiteplanURL           | Should provide        |
| Hectares              | Should provide        |
| OwnershipStatus       | Should provide        |
| PlanningStatus        | Should provide        |
| PermissionType        | Should provide        |
| PermissionDate        | Should provide        |
| PlanningHistory       | Should provide        |
| Deliverable           | Should provide        |
| NetDwellingsRangeFrom | Should provide        |
| NetDwellingsRangeTo   | Should provide        |
| HazardousSubstances   | Should provide        |
| Notes                 | Should provide        |
| FirstAddedDate        | Should provide        |
| LastUpdatedDate       | Should provide        |
| EndDate               | Should provide        |

**Comment by psd** [comment]
According to the legislation  `The register must contain the following information in relation to each entry of land in Part 1`

So we should be careful when giving feedback on this dataset not to undermine or mislead providers on their statutory duty, even though our platform can process registers just containing a reference, name and point (those are definitely the bare minimum).

We can also default the `OrganisationURI` value, which is empirically hard for LPAs to provide.

We can also add an optional `geometry` field for LPAs to provide the site boundary, where they have one.
 
`EndDate` is a MUST if the site has been developed or removed from the register.
These are things for the guidance as well:
