### ISSUE TITLE
Integrate guidance into the service

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#569]
## Context:

- Integrate guidance into the service, adding a navigation layer and bringing guidance pages into the service.

**Comment by alextea** [comment]
The [service navigation component](https://design-system.service.gov.uk/components/service-navigation/) should have the following text and links:

Service name: Submit and update your planning data 
This should link to the raw domain: https://submit.planning.data.gov.uk/

Navigation link 1: Find your organisation
This should link to the organisation finder: https://submit.planning.data.gov.uk/organisations

Navigation link 2: Guidance
This should link to the guidance (probably at /guidance)

![Screenshot 2024-10-23 at 12 36 22](https://github.com/user-attachments/assets/2885617f-f60e-4624-8339-75b1af9722ea)

The phase banner should be moved to the bottom of the page, below the content.

The [styling will need to be updated](https://github.com/digital-land/provider-design-sprint/blob/416319e08f0bdce62c624f14ddbd4e136d0fb527/app/assets/sass/application.scss#L116-L119) so it has a top-border

![Screenshot 2024-10-23 at 12 36 28](https://github.com/user-attachments/assets/9bb3493f-5d87-4494-b742-5e30e64d5b7b)
