### ISSUE TITLE
Update content and styling on check tool playback page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#571]
## Context:

- We have iterated on the layout, styling and content of the data playback and errors elsewhere in the service (on the dataset details page and dataset issues pages).
- The styling and content of the check tool now is out of sync with the rest of the service.

## Acceptance criteria:

- As a data provider, when I'm on the playback page of the check tool, the styling and content of the pages matches the latest designs:

![05a results](https://github.com/user-attachments/assets/15f7fe78-418b-4242-b483-e0da63824699)
![05b errors](https://github.com/user-attachments/assets/43ff0455-a74a-496f-ab61-5332d24910fb)

**Comment by alextea** [comment]
Links to the updated designs in the prototype:

[Errors page](https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/check/local-authority:LBH/article-4-direction/errors)
[Results page](https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/check/local-authority:LBH/article-4-direction/results)

**Comment by alextea** [comment]
![05a results](https://github.com/user-attachments/assets/15f7fe78-418b-4242-b483-e0da63824699)
![05b errors](https://github.com/user-attachments/assets/43ff0455-a74a-496f-ab61-5332d24910fb)

**Comment by GeorgeGoodall-GovUk** [comment]
just a note, the new table styling was implemented in my table branch. probably best I pick this up eventually as i can just cherry pick that code

**Comment by rosado** [comment]
Which page is the 'playback page'? Seems like the templates to update are the 'errors.html' and 'no-errors.html'

**Comment by rosado** [comment]
@CharliePatterson for the errors page, the error summary items look like links what are they supposed to link to?

**Comment by CharliePatterson** [comment]
Ah - I don't think they should be links. We use that styling on the entity-level issues pages, so that users can click on the issue and be shown the specific entity, though I don't think we need to do that in the table, as they can scroll through each one. It'd be good to check with @alextea though on the intended interaction here.

**Comment by alextea** [comment]
Sorry — I didn't see this comment. Could we change the text in the error summary to use these error messages: https://github.com/digital-land/submit/blob/main/src/content/fieldIssueMessages.csv

**Comment by rosado** [comment]
@alextea re: error messages - short answer is no, as in the [comment](https://github.com/digital-land/submit/pull/640#issuecomment-2474255293) on #645

**Comment by neilfwar** [comment]
will close and add new ticket to backlog for what alex is asking
