### ISSUE TITLE
Move guidance pages into submit service

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#572]
## Context:

- In the current iteration of the service the guidance lives outside of it, creating a disjointed and confusing journey for users (as evidenced through user research sessions).
- #573 will create a new navigation that enables users to more easily get to guidance pages from anywhere within the service, however, those pages would still exist outside of it, and thus be the UX equivalent of a culdesac.
- The scope of this ticket is to create a copy of the pages at https://www.planning.data.gov.uk/guidance/ and bring them into the submit repo, so that they exist within the service, including with the new navigation as per #573 

## Implementation details

- The current guidance sits in markdown files here: https://github.com/digital-land/digital-land.info/tree/main/application/templates/pages/guidance
- We want to keep the markdown files to ensure easy method of updating for content designers
- Create a guidance layout template to mirror what we currently have

**Comment by DilwoarH** [comment]
@CharliePatterson - added implementation details

Do we need another task to remove the guidance from the old repo and create redirects to the submit repo?

**Comment by CharliePatterson** [comment]
@DilwoarH ah, good shout 🙌 I'll spin up tickets for that.
