### ISSUE TITLE
Let LPAs know when their BFL datasets require updating

### ISSUE THREAD

**Issue by maddie-broxup** [digital-land/submit#579]
Find the clearest way of letting LPAs know when their brownfield land datasets need updating from the dashboard screen. 

We may end up using status indicators for this.

**Comment by maddie-broxup** [comment]
Chatted this through with Charlie today and looked over some design options (which are here in the Mural board: https://app.mural.co/t/mhclg2837/m/mhclg2837/1728654025264/16e0efd10d44506f2e66e5b02de469a99692b024?wid=0-1729869657414)

I've mocked up 2 options which we'd like to run through with Alex when he's back from holiday.

**Comment by maddie-broxup** [comment]
Brought this to our design crit on 30th Oct. Notes are here: https://app.mural.co/t/mhclg2837/m/mhclg2837/1729841459350/3c903499841bd18b161b2a1c8a7c778ac461c85b?wid=0-1730305088030

Will do a bit of a synth on these and chat to Alex / Charlie on Monday about next steps

**Comment by maddie-broxup** [comment]
Call with Charlie and Alex this morning to discuss possible options. Decided to move forwards with bringing the notification banner design into the LPA dashboard as a first instance. 

Further iterations to possibly include:

- adding more context into the landing page about datasets which funded LPAs must provide
- adding a notification into the task list

Alex will mock this up this afternoon

**Comment by maddie-broxup** [comment]
Finalised designs today with Alex and Charlie

**Comment by alextea** [comment]
## Dashboard

![Image](https://github.com/user-attachments/assets/89a9db68-0eae-406a-a8c4-5d174bdbae68)

## Dataset details

![Image](https://github.com/user-attachments/assets/59d1d259-393d-4e7b-9b8b-45221c6af9dc)
