### ISSUE TITLE
PLY Brownfield land dataset showing as not submitted

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#588]
## Context:

- Plymouth's brownfield land dataset is showing as 'Not submitted', even though they have 7 unique endpoints, and active data is showing on the platform.
- If you view [their dashboard](https://submit.planning.data.gov.uk/organisations/local-authority:PLY), you can see that the status is showing as 'Not submitted'.
- However, if you visit their [dataset details page for brownfield land](https://submit.planning.data.gov.uk/organisations/local-authority:PLY/brownfield-land/overview), you can see that data is being pulled through. Same when you run a [search on the platform](https://www.planning.data.gov.uk/entity/?dataset=brownfield-land&geometry_curie=statistical-geography%3AE06000026&entry_date_day=&entry_date_month=&entry_date_year=).
- It's not clear how many LPAs this is affecting, and whether it's restricted to brownfield land or affecting other datasets too.

**Comment by rosado** [comment]
Our overview page's [performance-db query] filters out issues with 'severity' info. Should we still be doing that?

[query]:https://datasette.planning.data.gov.uk/performance?sql=with+entity_counts+as+%28%0D%0Aselect+d+as+dataset%2C+r+as+resource%2C+e+as+entity_count%0D%0A++from+%28select+%27none%27+as+d%2C+%27none%27+as+r%2C+0+as+e%29+--+resource+is+not+given+here%2C+becaues+it%27s+issue+count+%3D+0%0D%0A%29%0D%0ASELECT%0D%0A++REPLACE%28rle.organisation%2C+%27-eng%27%2C+%27%27%29+as+organisation%2C%0D%0A++rle.name%2C%0D%0A++rle.pipeline+as+dataset%2C%0D%0A++rle.endpoint%2C%0D%0A++rle.resource%2C%0D%0A++rle.latest_exception%2C%0D%0A++rle.latest_status+as+http_status%2C%0D%0A++coalesce%28ec.entity_count%2C+0%29+as+entity_count%2C%0D%0A++i.count_issues+as+issue_count%2C%0D%0A++i.responsibility%2C%0D%0A++i.fields%2C%0D%0A++case%0D%0A++++++when+%28rle.latest_status+is+null%29+then+%27Not+submitted%27%0D%0A++++++when+%28rle.latest_status+%21%3D+%27200%27%29+then+%27Error%27%0D%0A++++++when+%28i.severity+%3D+%27error%27%29+then+%27Needs+fixing%27%0D%0A++++++else+%27Live%27%0D%0A++end+as+status%2C%0D%0A++case%0D%0A++++++when+%28%28cast%28rle.latest_status+as+integer%29+%3E+200%29%29+then+format%28%27There+was+a+%25s+error+accessing+the+data+URL%27%2C+rle.latest_status%29%0D%0A++++++else+null%0D%0A++end+as+error%2C%0D%0A++case%0D%0A++++++when+%28i.severity+%3D+%27info%27%29+then+%27%27%0D%0A++++++else+i.issue_type%0D%0A++end+as+issue_type%2C%0D%0A++case%0D%0A++++++when+%28i.severity+%3D+%27info%27%29+then+%27%27%0D%0A++++++else+i.severity%0D%0A++end+as+severity%0D%0AFROM%0D%0A++reporting_latest_endpoints+rle%0D%0ALEFT+JOIN%0D%0A++endpoint_dataset_issue_type_summary+i+ON+rle.resource+%3D+i.resource+AND+rle.pipeline+%3D+i.dataset%0D%0ALEFT+OUTER+JOIN%0D%0A++entity_counts+ec+ON+ec.resource+%3D+rle.resource+AND+ec.dataset+%3D+rle.pipeline%0D%0AWHERE%0D%0A++REPLACE%28rle.organisation%2C+%27-eng%27%2C+%27%27%29+%3D+%27local-authority%3APLY%27%0D%0A++AND+%28i.severity+is+NULL+OR+i.severity+not+in+%28%27info%27%29%29%0D%0A++AND+rle.pipeline+in+%28%27article-4-direction%27%2C%27article-4-direction-area%27%2C%27brownfield-land%27%2C%27conservation-area%27%2C%27conservation-area-document%27%2C%27tree-preservation-order%27%2C%27tree-preservation-zone%27%2C%27tree%27%2C%27listed-building%27%2C%27listed-building-outline%27%29%0D%0AORDER+BY%0D%0A++rle.organisation%2C%0D%0A++rle.name%3B

**Comment by CharliePatterson** [comment]
We shouldn't be including issues with severity type 'warning' or 'notice' (I think) when we're displaying a count of the total issues, or displaying a list of issues for the LPA to address. But that shouldn't affect whether or not the dashboard shows the submission status? They have data live on the platform, and so the dashboard should be reflecting that status.
