### ISSUE TITLE
Data quality issues not appearing on tasklist page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#597]
## Context:

- Data quality issues aren't being displayed on [Plymouth's task list page](https://submit.planning.data.gov.uk/organisations/local-authority:PLY/brownfield-land).
- They have two data quality issues that should be appearing on this page.
- Expected behaviour: the LPA should be able to see a task list of all data quality issues that require their attention (i.e. showing all data quality issues but excluding issues that are of severity type 'warning' or 'notice').

**Comment by GeorgeGoodall-GovUk** [comment]
archiving this as its a duplicate of #600
