### ISSUE TITLE
Check not accepting endpoints

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#608]
## Context:

The check tool isn't accepting some endpoints, and is returning a `The URL does not exist` error on the page:

---
![Image](https://github.com/user-attachments/assets/b3df7370-f8ae-4c7b-b134-18d455c6359a)
---

## Jira

13/11/2024: https://mhclgdigital.atlassian.net/browse/DLSD-1094

---

To replicate the issue, try running the following endpoint URLs through check:

- `https://maps.buckinghamshire.gov.uk/server/services/Planning/TPOs/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetCapabilities`
- `https://kingston.statmap.co.uk/map/wfs.svc/WFS_RBK_article4?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=statmap:RBK_article4&SRSNAME=EPSG:27700&outputFormat=application/json`
- *NEW* - https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities

A working assumption here is that it's not able to process these endpoints due to the fact that they're WFS endpoints, though that could be a red herring.

**Comment by GeorgeGoodall-GovUk** [comment]
@CharliePatterson @MJFaucherFolie 
FYI: the first of the two links https://maps.buckinghamshire.gov.uk/server/services/Planning/TPOs/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetCapabilities is timing out? not sure if this is a recent thing? 
I'll look at updating the message on our end for this error

**Comment by GeorgeGoodall-GovUk** [comment]
the first of the two links seems back online, but is still failing. lets try to fix that

**Comment by MJFaucherFolie** [comment]
Sorry to complicate things, but another LPA has flagged an issue with their WFS link:

https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities

**Comment by GeorgeGoodall-GovUk** [comment]
@CharliePatterson @MJFaucherFolie 
the first link still doesn't seem to be showing what's expected? 

https://maps.buckinghamshire.gov.uk/server/services/Planning/TPOs/MapServer/WFSServer?SERVICE=WFS&REQUEST=GetCapabilities

**Comment by GeorgeGoodall-GovUk** [comment]
@CharliePatterson @MJFaucherFolie 
the new link also seems to not have any data behind it? 

[ttps://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities](https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities)

should i close this ticket?

**Comment by MJFaucherFolie** [comment]
> [@CharliePatterson](https://github.com/CharliePatterson) [@MJFaucherFolie](https://github.com/MJFaucherFolie) the new link also seems to not have any data behind it?
> 
> [ttps://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities](https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities)
> 
> should i close this ticket?

The original link is an [XML file](https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?service%3Dwfs&request%3Dgetcapabilities)

Kena worked her magic and [converted it](https://dservices8.arcgis.com/SyngyOZB1zXVLSPX/arcgis/services/Article_4_direction_area_Broadland_WFS/WFSServer?request=GetFeature&service=WFS&TypeName=Article_4_direction_area_Broadland_polygons) so it is sharing the required data with us

**Comment by DilwoarH** [comment]
Head request was returning 500 error but the actual GET request was fine and returning 200.

I have updated the logic to only reject `404` - PR here: https://github.com/digital-land/submit/pull/734

cc @GeorgeGoodall-GovUk @CharliePatterson @MJFaucherFolie
