### ISSUE TITLE
Dashboard: Segment datasets into mandated and ODP

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#618]
## Context:

- Depending on whether or not an LPA is part of the ODP programme, they will be required to provide different datasets.
- All LPAs are legally mandated to supply two datasets (brownfield land and developer contributions), and those that are part of the ODP programme are required to supply four additional datasets (article 4, conservation area, listed building, tree preservation orders).
- Given that we are now encouraging non-ODP LPAs to use the service to submit their brownfield land, we want to make it clear to them which datasets they are required to provide, and which they can provide.
- We should also be ensuring that the list this page shows is dynamic rather than hard-coded, and is using the [provisions table](https://datasette.planning.data.gov.uk/digital-land/provision?_sort=rowid&organisation__exact=local-authority%3ACMD) to generate this list.
- However, using this list would mean integrating a new specification into the service (Developer contributions), which we're not set up to do yet. The proposed interim solution would be to manually hide this for now, through a list of datasets which the service supports.

## Acceptance criteria:

- As a data provider, when I'm viewing the dashboard, it is clear to me which datasets are required through legislation, and which are part of the ODP programme.

## Designs:

![image](https://github.com/user-attachments/assets/cb223460-b19d-49ea-9d8f-34e739fd1e24)

**Comment by rosado** [comment]
If a LPA has 'Open Digital Planning' in "project" column of the "provision" table, we put the extra text and "Important" box on the page? And the text is always the same? @CharliePatterson

**Comment by CharliePatterson** [comment]
Good question, thanks @rosado - sorry the original comment didn't have the full detail.

The 'important' box is being tackled in this ticket: https://github.com/digital-land/submit/issues/616

The scope of this work is to add in the segmentation to the dashboard into two separate lists:

1. Datasets that they must provide through legislation: i.e. `Statutory data` in the `provision_reason` column.
2. Datasets that are part of the ODP programme. For ODP LPAs this is signified by `Expected data`  in the `provision_reason` column.

If the LPA is part of the ODP programme (signified by the `Open Digital Planning` in the `project` column), then we should display the additional message:

> {LPA name} is a member of the Open Digital Planning programme.

We will need to hide the following datasets from the service for now:

1. Brownfield site
2. Developer agreement
3. Developer agreement contribution
4. Developer agreement transaction
5. Development plan
6. Development plan document
7. Development plan geography
8. Development plan timetable

Each of those seem to be labelled as `Prospective data`, however there are some other datasets with the same label that we do want to show (e.g. we want to show Article 4 direction area datasets for non-ODP LPAs).
