### ISSUE TITLE
End to end test for dataset overview and issue flow

### ISSUE THREAD

**Issue by DilwoarH** [digital-land/submit#621]
## What

Create an end to end test to test the following flow:

Landing page > /organisations > LPA overview > dataset overview > view issue tab

## Why

We want to increase coverage and stability of the platform

## Implementation details

- Ensure tests run on all environments, so do not assert things that are dynamic

**Comment by rosado** [comment]
> do not assert things that are dynamic

Whether a dataset has issues or not is dynamic - the underlying data changes.
