### ISSUE TITLE
Design comms plan to direct LPAs to the service to check and submit their BFL data

### ISSUE THREAD

**Issue by maddie-broxup** [digital-land/submit#627]
- [ ] Write content of comms
- [x] Decide frequency of comms

**Comment by maddie-broxup** [comment]
Initial notes from @paris-dp to kick off conversation tomorrow - https://app.mural.co/t/mhclg2837/m/mhclg2837/1728654025264/16e0efd10d44506f2e66e5b02de469a99692b024?wid=0-1732197494557

**Comment by paris-dp** [comment]
Comments added to draft email and message sent to Emma

**Comment by paris-dp** [comment]
Maddie and I drafted a possible LinkedIn post and shared this with psd. Amendments made and second draft created to share with comms. Email notification also amended in line with feedback. Link to drafts [here.](https://docs.google.com/document/d/1_jKYaPNmWFOoQ2jLrFI1AMG06OZgDqlEwYNaKEQ-Nnc/edit?tab=t.0#heading=h.xb2fyyl0f020)

**Comment by MJFaucherFolie** [comment]
Found emails for [282 LPAs](https://docs.google.com/spreadsheets/d/1SBuBqmsP4dUXhYprDjWhSQ96FqyasRsbkMRCWsYQBtY/edit?gid=733731380#gid=733731380) to send the messages to. Will export and share with Maddie and Paris ASAP 😁

**Comment by maddie-broxup** [comment]
Paul has approved the content for the LinkedIn post. I've shared this with Hannah Lomax in comms and asked if we can go live with it next week:

> Local planning authorities who have not yet reviewed and provided their brownfield land register for 2024 are required to do so by 31 December.
> 
> Use the service to review and provide your brownfield land register: https://submit.planning.data.gov.uk/.
> 
> The service will guide you through:
> 
> - checking your brownfield land register
> - publishing it
> - telling us where you’ve published your register
> 
> The Planning Data platform collects planning and housing data from local planning authorities (LPAs) and transforms it into a consistent state, across England. Anyone can view, download and analyse the data we hold: https://www.planning.data.gov.uk/.
> 
> We believe this will lead to:
> 
> - better planning decisions
> - fewer uncertainties and delays in the housing system
> - more new digital services for property and planning
> - better relationships between communities and developments

**Comment by maddie-broxup** [comment]
Email content has also been updated in Gov Notify to reflect Paul's comments. We will send this out on Monday:

> Dear ((LPA name)),
> 
> You’re required to review and update your brownfield land register by 31 December 2024. 
> 
> **How to update your brownfield land register**
> 
> Go to the service: ((UTM link)).
> 
> This will guide you through:
> 
> *checking your brownfield land register for errors
> *publishing it
> *telling us where you’ve published it
> 
> Use the guidance to help you: ((Guidance link)).
> 
> If you need further support, email us at DigitalLandTeam@communities.gov.uk.
> 
> Regards,
> Michael-Jordan Faucher-Folie on behalf of Digital Land, MHCLG

**Comment by maddie-broxup** [comment]
Email sent to LPAs at 10.30am today via Gov Notify
