### ISSUE TITLE
Text missing from dataset card on dashboard for broken/erroring endpoints

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#659]
- When an endpoint for a dataset is broken, the dataset card on the dashboard displays the `Error` status, and the content changes to alert the user that the endpoint is broken and requires attention.
- This content has now disappeared since a recent release:

![Image](https://github.com/user-attachments/assets/74a901ae-fa2e-49d8-b910-79c4f53b7388)

- See [Bristol's dashboard](https://submit.planning.data.gov.uk/organisations/local-authority:BST) for example.
- The content should read:

> There was an error accessing the data URL

**Comment by rosado** [comment]
The Bristol data changed so I can't see any datasets with "Error" status on the linked page, but [Barnsley (BNS)](https://submit.planning.data.gov.uk/organisations/local-authority:BNS) this one has some and the error message is there: 

![image](https://github.com/user-attachments/assets/5f229466-0742-4688-9da3-d8385b950d64)

The message on the page comes from the database, so it's possible there was no value/empty string there. We can provide a default message in that case.

**Comment by CharliePatterson** [comment]
Here's a live example: https://submit.planning.data.gov.uk/organisations/local-authority:BUC
