### ISSUE TITLE
Endpoint erroring state if dataset has multiple endpoints

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#671]
## Context:

- If a dataset has multiple active endpoints and one of them is erroring then:
   - Show the error message and status tag in the dataset card.
   - Include this in the "needs fixing" count.
- [This query](https://datasette.planning.data.gov.uk/performance/provision_summary?_sort=rowid&error_endpoint_count__gte=1&active_endpoint_count__gt=1&dataset__contains=brownfield) pulls through examples of LPAs with multiple endpoints where at least one of them is broken - e.g. https://submit.planning.data.gov.uk/organisations/local-authority:BAS

## Acceptance criteria:

- As a data provider, when I'm viewing our LPA dashboard page, and one of our active endpoints is broken, then the dashboard highlights this to me via the status tag in the dataset card, and the text in the card.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the overview middleware to aggregate dataset information correctly when there are multiple endpoints, and updated the overview template to display the appropriate status and error message.

You can review changes in this commit: https://github.com/lattaai13/digital-land-submit-671/commit/13ee1d499152c741bf2e8442e0c4c5c461cc849c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rosado** [comment]
What is the scope of the changes required? Seems like apart from updating the count pointed to by the red arrow on the screenshot below, we also need to update the count on the by the "Task List" tab heading on the specific dataset. But then the task list will need updating with one extra task?

![Image](https://github.com/user-attachments/assets/770fef0b-3afa-420d-aa56-661c7b7da13a)

**Comment by CharliePatterson** [comment]
When there's a broken endpoint, the text in the dataset card on the dashboard changes to something different (though that's broken at the moment, see: https://github.com/digital-land/submit/issues/659 - so, it might make sense to fix that bug first?).

The scope of this is to change the logic on the dataset card on the dashboard page, so that it checks all active endpoints and if one of those endpoints is broken, then the dataset card should:

- Show the `There was an error accessing the data URL` message
- Display the `Error` tag

In terms of changing the issue count on the task list navigation item: not in scope for this piece, but should be covered as part of [this piece of work](https://github.com/digital-land/submit/issues/669).
