### ISSUE TITLE
SPIKE: Identify a method to store and read key values from Google Sheets

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#675]
## Context
- As part of automating the Service Message process, we are proposing to use Google sheets as a temporary solution for storing contact information for LPAs.
- We need a way to read the key values within the google sheet, so that we can send emails.
The focus of this ticket is understanding how we can read relevant information from the google sheet itself.

## Acceptance criteria 
- Understand how we can read information from a Google sheet

**Comment by MJFaucherFolie** [comment]
Use google sheets 
knowing where endpoints sit - subscribe and unsub - when it clicks - our sheets react to it

two spreadsheets - one for LPAs, another for anyone else who wants to subscribe 

**Focus on community managers first**. Manage popularity and use that to gage when to implement the second version (then look at the front end of it)

**Comment by MJFaucherFolie** [comment]
Taking key values (LPA emails and the content)

Script - at first, focus on basic messaging. Iterate over time (more detailed message)

**Comment by MJFaucherFolie** [comment]
Reading the google sheet

Make spike around generating content

**Comment by CharliePatterson** [comment]
A couple of additional things to consider here:

- We're using MS Dataverse as the backend for the ODP CRM - i.e. to store all the contact information for each of the LPAs. How does this fit into the picture? Can we use this directly, or do we need to get the data from MS Dataverse into a Google Sheet?
- We should involve the Infrastructure folks (Owen, Ben) in this.

**Comment by DilwoarH** [comment]
> A couple of additional things to consider here:
> 
> * We're using MS Dataverse as the backend for the ODP CRM - i.e. to store all the contact information for each of the LPAs. How does this fit into the picture? Can we use this directly, or do we need to get the data from MS Dataverse into a Google Sheet?
> * We should involve the Infrastructure folks (Owen, Ben) in this.

Could we directly connect to the CRM via their APIs and pull in the needed information? This will avoid the need to have any sort of data stored in google sheets etc.

**Comment by DilwoarH** [comment]
I have done the spike on the google sheets integration.

Google sheet:

```
https://docs.google.com/spreadsheets/d/1Qe5_EOQNJlMNVHcyLhLTKvnDppDxypdYF1b7D0zz3ME/edit?pli=1&gid=0#gid=0
```

Code:

```js
const { google } = require('googleapis');
const path = require('path');

// Path to your service account key file
const SERVICE_ACCOUNT_FILE = path.join(__dirname, 'service-account-key.json');

// The ID of your Google Sheet
const SHEET_ID = '1Qe5_EOQNJlMNVHcyLhLTKvnDppDxypdYF1b7D0zz3ME'; // Replace with your Google Sheet ID

// The range of cells to read (e.g., "Sheet1!A1:E10")
const RANGE = 'Sheet1!A1:B100';

// Function to authenticate and fetch data
async function readGoogleSheet() {
  try {
    // Authenticate with the service account
    const auth = new google.auth.GoogleAuth({
      keyFile: SERVICE_ACCOUNT_FILE,
      scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
    });

    // Create the Sheets API client
    const sheets = google.sheets({ version: 'v4', auth });

    // Fetch the data
    const response = await sheets.spreadsheets.values.get({
      spreadsheetId: SHEET_ID,
      range: RANGE,
    });

    // Log the data to the console
    const rows = response.data.values;
    if (rows.length) {
      console.log('Data from the sheet:');
      rows.forEach((row) => {
        console.log(row);
      });
    } else {
      console.log('No data found in the specified range.');
    }
  } catch (error) {
    console.error('Error reading Google Sheet:', error.message);
  }
}

// Call the function
readGoogleSheet();
```

Result:

```
Data from the sheet:
[ 'Name', 'Email' ]
[ 'Test 1', 'test1@gmail.com' ]
[ 'Test 2', 'test1@gmail.com' ]
[ 'Test 3', 'test1@gmail.com' ]
[ 'Test 4', 'test1@gmail.com' ]
[ 'Test 5', 'test1@gmail.com' ]
[ 'Test 6', 'test1@gmail.com' ]
[ 'Test 7', 'test1@gmail.com' ]
[ 'Test 8', 'test1@gmail.com' ]
[ 'Test 9', 'test1@gmail.com' ]
[ 'Test 10', 'test1@gmail.com' ]
[ 'Test 11', 'test1@gmail.com' ]
[ 'Test 12', 'test1@gmail.com' ]
[ 'Test 13', 'test1@gmail.com' ]
[ 'Test 14', 'test1@gmail.com' ]
[ 'Test 15', 'test1@gmail.com' ]
[ 'Test 16', 'test1@gmail.com' ]
[ 'Test 17', 'test1@gmail.com' ]
[ 'Test 18', 'test1@gmail.com' ]
[ 'Test 19', 'test1@gmail.com' ]
[ 'Test 20', 'test1@gmail.com' ]
[ 'Test 21', 'test1@gmail.com' ]
[ 'Test 22', 'test1@gmail.com' ]
[ 'Test 23', 'test1@gmail.com' ]
[ 'Test 24', 'test1@gmail.com' ]
[ 'Test 25', 'test1@gmail.com' ]
[ 'Test 26', 'test1@gmail.com' ]
[ 'Test 27', 'test1@gmail.com' ]
[ 'Test 28', 'test1@gmail.com' ]
[ 'Test 29', 'test1@gmail.com' ]
[ 'Test 30', 'test1@gmail.com' ]
[ 'Test 31', 'test1@gmail.com' ]
```

**Comment by neilfwar** [comment]
> > A couple of additional things to consider here:
> > 
> > * We're using MS Dataverse as the backend for the ODP CRM - i.e. to store all the contact information for each of the LPAs. How does this fit into the picture? Can we use this directly, or do we need to get the data from MS Dataverse into a Google Sheet?
> > * We should involve the Infrastructure folks (Owen, Ben) in this.
> 
> Could we directly connect to the CRM via their APIs and pull in the needed information? This will avoid the need to have any sort of data stored in google sheets etc.

@eveleighoj - Gordon has asked for ticket ref this - if you can access to the LPA contact details data tables in  ODP CRM which is https://apps.powerapps.com/play/e/932a0d53-11ad-ee65-9922-dfc8436063ac/a/1984da22-6944-4c73-82ec-56da6b53c623?tenantId=bf346810-9c7d-43de-a872-24a2ef3995a8&hint=f67a9321-5382-42de-b7e9-086678ddd4cd&sourcetime=1718185463010&source=portal
I have requested Prod access for you with his but seems to be taking a while for IT to understand the request and they closed the original request saying you had access
