### ISSUE TITLE
West Berkshire TPZ issues not loading

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#704]
### Summary Description
- West Berkshire TPZ data has issues, but clicking into them results with an error
 
### Environment (OS, Browser,device, app version, network)
- Desktop
 
###  Steps to reproduce it
1. Access [West Berkshire's dashboard](https://submit.planning.data.gov.uk/organisations/local-authority:WBK/tree-preservation-zone)
2. Select TPZ 
3. Click on any of the issues
 
### Expected behaviour (Include screenshots if applicable)
- Show the table and identify the issues related to it

### Actual Behaviour(include screenshots if applicable)
 ![Image](https://github.com/user-attachments/assets/4ce2ccbb-b324-4b6e-81ff-a016f67d6a02)

### Frequency (how often/how many users/when)
how often: 1 dataset
how many users: 1 LPA 
when does it occur: when trying to access information about issues
 
### Impact/ Priority (user/system)
P1 high - affects core functions

 ### Possible workaround
- None

**Comment by DilwoarH** [comment]
This seems to be resolved @MJFaucherFolie - can we close it?

**Comment by MJFaucherFolie** [comment]
Perfect! Will close the ticket. Thanks for the update Dilwoar!
